import type { StrainProfile } from "./types";

// Curated reference dataset. SOMA is not a strain encyclopedia — this set
// exists only to give the Taste Match Engine sensory anchors. Real batch
// quality always depends on grower, freshness and storage.
export const STRAINS: StrainProfile[] = [
  // ── GAS / OG CLASSICS ──
  {
    name: "GG4",
    aliases: ["Gorilla Glue #4", "Gorilla Glue", "Original Glue", "Glue", "GG#4"],
    type: "hybrid",
    aromas: ["gassy", "earthy", "pine", "diesel"],
    flavors: ["earthy", "pine", "gassy"],
    effects: ["relaxed", "euphoric", "body-heavy", "happy", "calm"],
    traits: ["gassy", "earthy", "sticky", "loud-smell", "heavy-body", "frosty", "potent"],
    potency: "very-strong",
    note: "The benchmark gas-and-earth hybrid: heavy body, sticky resin, loud nose.",
  },
  {
    name: "OG Kush",
    aliases: ["OG"],
    type: "hybrid",
    aromas: ["gassy", "earthy", "pine", "woody"],
    flavors: ["earthy", "pine", "woody", "gassy"],
    effects: ["relaxed", "euphoric", "happy", "body-heavy", "calm"],
    traits: ["gassy", "earthy", "loud-smell", "dense-buds", "potent"],
    potency: "strong",
  },
  {
    name: "Chemdawg",
    aliases: ["Chemdog", "Chem Dawg", "Chem"],
    type: "hybrid",
    aromas: ["diesel", "gassy", "earthy", "pine"],
    flavors: ["diesel", "earthy", "gassy"],
    effects: ["euphoric", "relaxed", "happy", "head-high", "calm"],
    traits: ["gassy", "loud-smell", "sticky", "potent"],
    potency: "very-strong",
  },
  {
    name: "Sour Diesel",
    aliases: ["Sour D", "Sour Deez"],
    type: "sativa",
    aromas: ["diesel", "gassy", "citrus", "skunky"],
    flavors: ["gassy", "citrus", "herbal"],
    effects: ["energetic", "uplifted", "euphoric", "head-high", "creative"],
    traits: ["gassy", "loud-smell", "terpy", "potent"],
    potency: "strong",
  },
  {
    name: "Skywalker OG",
    aliases: ["Skywalker"],
    type: "indica",
    aromas: ["gassy", "earthy", "herbal", "spicy"],
    flavors: ["gassy", "earthy", "herbal"],
    effects: ["relaxed", "sleepy", "body-heavy", "couch-lock", "calm"],
    traits: ["gassy", "dense-buds", "heavy-body", "potent"],
    potency: "very-strong",
  },
  {
    name: "GMO Cookies",
    aliases: ["GMO", "Garlic Cookies", "Garlic Breath"],
    type: "indica",
    aromas: ["gassy", "earthy", "spicy", "herbal"],
    flavors: ["gassy", "earthy", "spicy", "herbal"],
    effects: ["relaxed", "body-heavy", "couch-lock", "euphoric", "sleepy"],
    traits: ["gassy", "loud-smell", "frosty", "heavy-body", "potent", "terpy"],
    potency: "very-strong",
  },
  {
    name: "Tahoe OG",
    type: "indica",
    aromas: ["gassy", "earthy", "pine", "woody"],
    flavors: ["gassy", "earthy", "pine"],
    effects: ["relaxed", "body-heavy", "couch-lock", "sleepy", "euphoric"],
    traits: ["gassy", "heavy-body", "dense-buds", "potent", "frosty"],
    potency: "very-strong",
  },
  {
    name: "King Louis XIII",
    aliases: ["King Louis", "King Louie"],
    type: "indica",
    aromas: ["gassy", "earthy", "pine", "spicy"],
    flavors: ["gassy", "earthy", "pine"],
    effects: ["relaxed", "body-heavy", "sleepy", "couch-lock", "calm"],
    traits: ["gassy", "earthy", "dense-buds", "heavy-body", "potent"],
    potency: "very-strong",
  },
  {
    name: "Platinum OG",
    aliases: ["Plat OG"],
    type: "indica",
    aromas: ["gassy", "earthy", "spicy"],
    flavors: ["earthy", "gassy", "herbal"],
    effects: ["relaxed", "sleepy", "body-heavy", "couch-lock", "euphoric"],
    traits: ["heavy-body", "potent", "frosty", "dense-buds"],
    potency: "very-strong",
  },
  {
    name: "Fire OG",
    type: "hybrid",
    aromas: ["gassy", "citrus", "earthy", "pine"],
    flavors: ["gassy", "citrus", "earthy"],
    effects: ["relaxed", "euphoric", "body-heavy", "happy", "sleepy"],
    traits: ["gassy", "frosty", "loud-smell", "potent", "heavy-body"],
    potency: "very-strong",
  },
  {
    name: "Face Off OG",
    aliases: ["Face Off"],
    type: "indica",
    aromas: ["gassy", "earthy", "pine", "diesel"],
    flavors: ["gassy", "earthy", "pine"],
    effects: ["relaxed", "body-heavy", "couch-lock", "sleepy", "calm"],
    traits: ["gassy", "heavy-body", "potent", "dense-buds", "frosty"],
    potency: "very-strong",
  },
  {
    name: "Alien OG",
    type: "hybrid",
    aromas: ["gassy", "earthy", "pine", "citrus"],
    flavors: ["gassy", "earthy", "pine"],
    effects: ["euphoric", "relaxed", "body-heavy", "happy", "head-high"],
    traits: ["gassy", "frosty", "potent", "loud-smell"],
    potency: "very-strong",
  },
  {
    name: "SFV OG",
    aliases: ["San Fernando Valley OG"],
    type: "sativa",
    aromas: ["gassy", "earthy", "pine", "herbal"],
    flavors: ["gassy", "earthy", "pine"],
    effects: ["euphoric", "uplifted", "relaxed", "focused", "happy"],
    traits: ["gassy", "terpy", "frosty"],
    potency: "strong",
  },
  {
    name: "Headband",
    aliases: ["HB"],
    type: "hybrid",
    aromas: ["diesel", "gassy", "citrus", "earthy"],
    flavors: ["diesel", "citrus", "earthy"],
    effects: ["relaxed", "euphoric", "focused", "calm", "happy"],
    traits: ["gassy", "terpy"],
    potency: "strong",
  },
  {
    name: "Chem 91",
    aliases: ["Chemdog 91", "Chem 91 Skunk Va"],
    type: "hybrid",
    aromas: ["diesel", "gassy", "earthy", "pine"],
    flavors: ["diesel", "earthy", "gassy"],
    effects: ["euphoric", "uplifted", "relaxed", "creative", "head-high"],
    traits: ["gassy", "loud-smell", "sticky", "potent"],
    potency: "very-strong",
  },
  {
    name: "Motorbreath",
    type: "indica",
    aromas: ["diesel", "gassy", "earthy", "spicy"],
    flavors: ["diesel", "earthy", "gassy"],
    effects: ["relaxed", "body-heavy", "euphoric", "sleepy", "couch-lock"],
    traits: ["gassy", "loud-smell", "heavy-body", "potent", "frosty"],
    potency: "very-strong",
  },
  {
    name: "Sour OG",
    type: "hybrid",
    aromas: ["diesel", "gassy", "earthy", "citrus"],
    flavors: ["diesel", "citrus", "earthy"],
    effects: ["euphoric", "relaxed", "uplifted", "happy", "calm"],
    traits: ["gassy", "terpy", "loud-smell"],
    potency: "strong",
  },
  {
    name: "Donny Burger",
    type: "hybrid",
    aromas: ["gassy", "earthy", "cheese", "spicy"],
    flavors: ["gassy", "earthy", "spicy"],
    effects: ["relaxed", "euphoric", "body-heavy", "couch-lock", "happy"],
    traits: ["gassy", "loud-smell", "heavy-body", "frosty", "potent"],
    potency: "very-strong",
  },
  {
    name: "Permanent Marker",
    type: "hybrid",
    aromas: ["gassy", "sweet", "earthy", "diesel"],
    flavors: ["gassy", "sweet", "earthy"],
    effects: ["euphoric", "relaxed", "happy", "uplifted", "body-heavy"],
    traits: ["gassy", "loud-smell", "frosty", "potent", "sticky"],
    potency: "very-strong",
  },
  {
    name: "Gas Face",
    type: "hybrid",
    aromas: ["gassy", "earthy", "diesel", "spicy"],
    flavors: ["gassy", "earthy", "spicy"],
    effects: ["relaxed", "euphoric", "body-heavy", "happy", "calm"],
    traits: ["gassy", "loud-smell", "frosty", "potent"],
    potency: "very-strong",
  },
  {
    name: "Triple Double OG",
    aliases: ["Triple OG", "TD OG"],
    type: "indica",
    aromas: ["gassy", "earthy", "pine", "diesel"],
    flavors: ["gassy", "earthy", "pine"],
    effects: ["relaxed", "body-heavy", "euphoric", "couch-lock", "calm"],
    traits: ["gassy", "earthy", "loud-smell", "heavy-body", "dense-buds", "potent"],
    potency: "very-strong",
    note: "Heavy gas-forward OG — close in spirit to a GG4 body profile.",
  },
  {
    name: "Triangle Kush",
    aliases: ["TK"],
    type: "indica",
    aromas: ["gassy", "earthy", "pine", "herbal"],
    flavors: ["gassy", "earthy", "pine"],
    effects: ["relaxed", "euphoric", "body-heavy", "calm", "happy"],
    traits: ["gassy", "loud-smell", "dense-buds", "potent"],
    potency: "strong",
    note: "Florida OG phenotype — genetic backbone of Permanent Marker, Triangle Mints and a long list of modern indica hybrids.",
  },

  // ── KUSH / INDICA CLASSICS ──
  {
    name: "Northern Lights",
    aliases: ["NL"],
    type: "indica",
    aromas: ["earthy", "pine", "sweet", "spicy"],
    flavors: ["sweet", "earthy", "pine"],
    effects: ["relaxed", "sleepy", "body-heavy", "happy", "calm"],
    traits: ["earthy", "dense-buds", "smooth", "heavy-body"],
    potency: "strong",
  },
  {
    name: "Granddaddy Purple",
    aliases: ["GDP", "Grand Daddy Purple", "Granddaddy Purp"],
    type: "indica",
    aromas: ["berry", "sweet", "floral", "fruity"],
    flavors: ["grape", "berry", "sweet"],
    effects: ["relaxed", "sleepy", "body-heavy", "couch-lock", "happy"],
    traits: ["dense-buds", "smooth", "heavy-body", "frosty"],
    potency: "strong",
  },
  {
    name: "Bubba Kush",
    aliases: ["Bubba", "BK"],
    type: "indica",
    aromas: ["earthy", "sweet", "gassy", "woody", "spicy"],
    flavors: ["earthy", "sweet", "woody", "spicy"],
    effects: ["relaxed", "sleepy", "body-heavy", "couch-lock", "calm"],
    traits: ["heavy-body", "dense-buds", "smooth", "potent"],
    potency: "strong",
  },
  {
    name: "Master Kush",
    type: "indica",
    aromas: ["earthy", "woody", "spicy", "citrus"],
    flavors: ["earthy", "woody", "spicy"],
    effects: ["relaxed", "sleepy", "body-heavy", "happy", "calm"],
    traits: ["earthy", "dense-buds", "smooth", "heavy-body"],
    potency: "strong",
  },
  {
    name: "Hindu Kush",
    type: "indica",
    aromas: ["earthy", "woody", "spicy", "herbal"],
    flavors: ["earthy", "woody", "herbal"],
    effects: ["relaxed", "sleepy", "body-heavy", "calm", "couch-lock"],
    traits: ["earthy", "smooth", "heavy-body", "dense-buds"],
    potency: "moderate",
  },
  {
    name: "Afghani",
    aliases: ["Afghan", "Afghan Kush"],
    type: "indica",
    aromas: ["earthy", "woody", "spicy", "sweet"],
    flavors: ["earthy", "woody", "sweet"],
    effects: ["relaxed", "sleepy", "body-heavy", "couch-lock", "hungry"],
    traits: ["earthy", "heavy-body", "dense-buds", "sticky"],
    potency: "strong",
  },
  {
    name: "LA Confidential",
    aliases: ["LA Conf"],
    type: "indica",
    aromas: ["earthy", "pine", "gassy", "woody"],
    flavors: ["earthy", "pine", "woody"],
    effects: ["relaxed", "sleepy", "body-heavy", "couch-lock", "calm"],
    traits: ["dense-buds", "earthy", "heavy-body", "potent"],
    potency: "strong",
  },
  {
    name: "Kosher Kush",
    aliases: ["Kosher OG", "KK"],
    type: "indica",
    aromas: ["earthy", "pine", "woody", "spicy"],
    flavors: ["earthy", "pine", "woody"],
    effects: ["relaxed", "body-heavy", "sleepy", "couch-lock", "euphoric"],
    traits: ["earthy", "heavy-body", "dense-buds", "potent", "frosty"],
    potency: "very-strong",
  },
  {
    name: "Critical Mass",
    aliases: ["Critical"],
    type: "indica",
    aromas: ["sweet", "earthy", "spicy", "woody"],
    flavors: ["sweet", "earthy", "woody"],
    effects: ["relaxed", "body-heavy", "sleepy", "happy", "hungry"],
    traits: ["dense-buds", "smooth", "heavy-body"],
    potency: "moderate",
  },
  {
    name: "9 Pound Hammer",
    aliases: ["9lb Hammer"],
    type: "indica",
    aromas: ["fruity", "earthy", "woody", "pine"],
    flavors: ["fruity", "earthy", "woody"],
    effects: ["relaxed", "body-heavy", "couch-lock", "sleepy", "calm"],
    traits: ["heavy-body", "dense-buds", "smooth"],
    potency: "strong",
  },
  {
    name: "Do-Si-Dos",
    aliases: ["Dosidos", "Dosi"],
    type: "indica",
    aromas: ["sweet", "earthy", "gassy", "floral"],
    flavors: ["sweet", "earthy", "gassy", "herbal"],
    effects: ["relaxed", "body-heavy", "couch-lock", "euphoric", "sleepy"],
    traits: ["frosty", "sticky", "heavy-body", "potent", "terpy"],
    potency: "very-strong",
  },
  {
    name: "Slurricane",
    type: "indica",
    aromas: ["fruity", "sweet", "berry", "earthy"],
    flavors: ["fruity", "sweet", "berry", "grape"],
    effects: ["relaxed", "body-heavy", "couch-lock", "sleepy", "euphoric"],
    traits: ["heavy-body", "frosty", "dense-buds", "potent"],
    potency: "very-strong",
  },
  {
    name: "Pink Kush",
    type: "indica",
    aromas: ["floral", "sweet", "earthy", "gassy"],
    flavors: ["sweet", "floral", "earthy"],
    effects: ["relaxed", "sleepy", "body-heavy", "euphoric", "calm"],
    traits: ["dense-buds", "heavy-body", "potent", "frosty"],
    potency: "strong",
    note: "OG Kush phenotype with a floral-candy nose — heavy late-night indica.",
  },
  {
    name: "Mendo Breath",
    aliases: ["Mendo"],
    type: "indica",
    aromas: ["gassy", "earthy", "sweet", "vanilla"],
    flavors: ["gassy", "earthy", "sweet", "vanilla"],
    effects: ["relaxed", "body-heavy", "sleepy", "euphoric", "calm"],
    traits: ["gassy", "sticky", "frosty", "heavy-body", "potent"],
    potency: "very-strong",
  },
  {
    name: "Yoda OG",
    type: "indica",
    aromas: ["gassy", "earthy", "pine", "woody"],
    flavors: ["gassy", "earthy", "pine"],
    effects: ["relaxed", "sleepy", "body-heavy", "couch-lock", "calm"],
    traits: ["gassy", "dense-buds", "heavy-body", "potent"],
    potency: "very-strong",
  },
  {
    name: "Afgooey",
    aliases: ["Afghan Goo"],
    type: "indica",
    aromas: ["earthy", "gassy", "herbal", "woody"],
    flavors: ["earthy", "gassy", "herbal"],
    effects: ["relaxed", "sleepy", "body-heavy", "couch-lock", "happy"],
    traits: ["sticky", "gassy", "heavy-body", "potent"],
    potency: "strong",
  },
  {
    name: "Ice",
    aliases: ["I.C.E.", "Indica Crystal Extreme"],
    type: "indica",
    aromas: ["earthy", "herbal", "spicy", "skunky"],
    flavors: ["earthy", "herbal", "spicy"],
    effects: ["relaxed", "sleepy", "body-heavy", "couch-lock", "euphoric"],
    traits: ["frosty", "heavy-body", "dense-buds", "potent"],
    potency: "strong",
    note: "ICE = Indica Crystal Extreme. Trichome-dense and seriously sedating — name lives up.",
  },
  {
    name: "Black Domina",
    type: "indica",
    aromas: ["earthy", "spicy", "herbal", "woody"],
    flavors: ["earthy", "spicy", "herbal", "woody"],
    effects: ["relaxed", "sleepy", "body-heavy", "couch-lock", "calm"],
    traits: ["dense-buds", "heavy-body", "potent"],
    potency: "strong",
  },
  {
    name: "Critical Kush",
    type: "indica",
    aromas: ["gassy", "earthy", "herbal", "sweet"],
    flavors: ["gassy", "earthy", "herbal", "sweet"],
    effects: ["relaxed", "sleepy", "body-heavy", "euphoric", "calm"],
    traits: ["dense-buds", "heavy-body", "potent"],
    potency: "strong",
  },
  {
    name: "Master Yoda",
    type: "indica",
    aromas: ["gassy", "earthy", "pine", "woody"],
    flavors: ["gassy", "earthy", "pine", "woody"],
    effects: ["relaxed", "sleepy", "body-heavy", "couch-lock", "calm"],
    traits: ["gassy", "dense-buds", "heavy-body", "potent"],
    potency: "very-strong",
  },

  // ── PURPLE / BERRY ──
  {
    name: "Purple Punch",
    type: "indica",
    aromas: ["berry", "sweet", "fruity", "floral"],
    flavors: ["grape", "berry", "sweet", "vanilla"],
    effects: ["relaxed", "sleepy", "body-heavy", "happy", "hungry"],
    traits: ["dense-buds", "frosty", "smooth"],
    potency: "strong",
  },
  {
    name: "Purple Urkle",
    aliases: ["Urkle"],
    type: "indica",
    aromas: ["berry", "sweet", "fruity", "earthy"],
    flavors: ["grape", "berry", "sweet"],
    effects: ["relaxed", "sleepy", "body-heavy", "happy", "calm"],
    traits: ["smooth", "dense-buds", "heavy-body"],
    potency: "strong",
  },
  {
    name: "Grape Ape",
    type: "indica",
    aromas: ["berry", "sweet", "fruity", "earthy"],
    flavors: ["grape", "berry", "sweet"],
    effects: ["relaxed", "sleepy", "body-heavy", "happy", "calm"],
    traits: ["smooth", "dense-buds"],
    potency: "strong",
  },
  {
    name: "Blackberry Kush",
    type: "indica",
    aromas: ["berry", "sweet", "earthy", "floral"],
    flavors: ["berry", "sweet", "earthy"],
    effects: ["relaxed", "sleepy", "body-heavy", "happy", "calm"],
    traits: ["smooth", "dense-buds", "heavy-body"],
    potency: "strong",
  },
  {
    name: "Blueberry",
    aliases: ["Blueberry Kush"],
    type: "indica",
    aromas: ["berry", "sweet", "fruity", "earthy"],
    flavors: ["berry", "sweet", "fruity"],
    effects: ["relaxed", "happy", "sleepy", "body-heavy", "calm"],
    traits: ["smooth", "dense-buds", "terpy"],
    potency: "moderate",
  },
  {
    name: "Purple Haze",
    type: "sativa",
    aromas: ["berry", "sweet", "earthy", "spicy"],
    flavors: ["berry", "sweet", "earthy"],
    effects: ["uplifted", "energetic", "happy", "creative", "euphoric"],
    traits: ["smooth", "terpy"],
    potency: "moderate",
  },
  {
    name: "Berry White",
    aliases: ["Blue Widow"],
    type: "hybrid",
    aromas: ["berry", "sweet", "floral", "earthy"],
    flavors: ["berry", "sweet", "floral"],
    effects: ["relaxed", "euphoric", "happy", "calm", "uplifted"],
    traits: ["smooth", "frosty", "terpy"],
    potency: "strong",
  },
  {
    name: "Cherry Pie",
    type: "hybrid",
    aromas: ["sweet", "berry", "earthy", "fruity"],
    flavors: ["berry", "sweet", "earthy", "fruity"],
    effects: ["relaxed", "happy", "euphoric", "uplifted", "calm"],
    traits: ["smooth", "terpy"],
    potency: "moderate",
  },
  {
    name: "Cherry Punch",
    type: "hybrid",
    aromas: ["berry", "sweet", "fruity", "floral"],
    flavors: ["berry", "sweet", "fruity"],
    effects: ["relaxed", "happy", "euphoric", "uplifted", "calm"],
    traits: ["smooth", "frosty", "terpy"],
    potency: "strong",
  },

  // ── COOKIES / DESSERT FAMILY ──
  {
    name: "Girl Scout Cookies",
    aliases: ["GSC", "Cookies"],
    type: "hybrid",
    aromas: ["sweet", "earthy", "spicy", "herbal"],
    flavors: ["sweet", "earthy", "spicy"],
    effects: ["euphoric", "happy", "relaxed", "body-heavy", "head-high"],
    traits: ["frosty", "dense-buds", "potent", "terpy"],
    potency: "very-strong",
  },
  {
    name: "Wedding Cake",
    aliases: ["Pink Cookies", "Triangle Mints"],
    type: "hybrid",
    aromas: ["sweet", "earthy", "creamy", "spicy"],
    flavors: ["sweet", "vanilla", "earthy", "creamy"],
    effects: ["relaxed", "euphoric", "happy", "body-heavy", "calm"],
    traits: ["frosty", "dense-buds", "sticky", "potent", "terpy"],
    potency: "very-strong",
  },
  {
    name: "Sunset Sherbet",
    aliases: ["Sherbet", "Sherbert"],
    type: "hybrid",
    aromas: ["sweet", "fruity", "citrus", "earthy"],
    flavors: ["sweet", "fruity", "citrus", "creamy"],
    effects: ["relaxed", "euphoric", "happy", "uplifted", "calm"],
    traits: ["frosty", "terpy", "sticky"],
    potency: "strong",
  },
  {
    name: "Animal Cookies",
    aliases: ["Animal OG"],
    type: "indica",
    aromas: ["sweet", "earthy", "spicy", "gassy"],
    flavors: ["sweet", "earthy", "spicy"],
    effects: ["relaxed", "body-heavy", "euphoric", "sleepy", "couch-lock"],
    traits: ["frosty", "dense-buds", "heavy-body", "potent"],
    potency: "very-strong",
  },
  {
    name: "Animal Mints",
    type: "hybrid",
    aromas: ["sweet", "earthy", "gassy", "herbal"],
    flavors: ["sweet", "earthy", "mint", "herbal"],
    effects: ["relaxed", "euphoric", "body-heavy", "calm", "happy"],
    traits: ["frosty", "dense-buds", "potent", "terpy"],
    potency: "very-strong",
  },
  {
    name: "Biscotti",
    type: "hybrid",
    aromas: ["sweet", "earthy", "gassy", "spicy"],
    flavors: ["sweet", "earthy", "spicy", "nutty"],
    effects: ["relaxed", "euphoric", "happy", "body-heavy", "calm"],
    traits: ["frosty", "sticky", "dense-buds", "potent", "terpy"],
    potency: "very-strong",
  },
  {
    name: "London Pound Cake",
    aliases: ["LPC", "Pound Cake"],
    type: "indica",
    aromas: ["sweet", "berry", "fruity", "earthy"],
    flavors: ["sweet", "berry", "fruity", "vanilla"],
    effects: ["relaxed", "euphoric", "happy", "body-heavy", "calm"],
    traits: ["frosty", "dense-buds", "potent", "terpy"],
    potency: "very-strong",
  },
  {
    name: "Gary Payton",
    aliases: ["GP", "The Y"],
    type: "hybrid",
    aromas: ["gassy", "earthy", "sweet", "spicy"],
    flavors: ["gassy", "earthy", "sweet"],
    effects: ["euphoric", "uplifted", "relaxed", "happy", "focused"],
    traits: ["frosty", "gassy", "loud-smell", "potent", "terpy"],
    potency: "very-strong",
  },
  {
    name: "Kush Mints",
    aliases: ["Kushmintz"],
    type: "hybrid",
    aromas: ["gassy", "earthy", "sweet", "herbal"],
    flavors: ["earthy", "mint", "sweet", "herbal"],
    effects: ["relaxed", "euphoric", "body-heavy", "calm", "focused"],
    traits: ["frosty", "gassy", "dense-buds", "potent", "terpy"],
    potency: "very-strong",
  },
  {
    name: "Cereal Milk",
    type: "hybrid",
    aromas: ["sweet", "creamy", "fruity", "citrus"],
    flavors: ["sweet", "creamy", "fruity", "vanilla"],
    effects: ["relaxed", "euphoric", "happy", "uplifted", "calm"],
    traits: ["frosty", "terpy", "smooth"],
    potency: "strong",
  },
  {
    name: "Mochi",
    aliases: ["Mochi Gelato"],
    type: "hybrid",
    aromas: ["sweet", "fruity", "earthy", "herbal"],
    flavors: ["sweet", "fruity", "creamy"],
    effects: ["relaxed", "euphoric", "happy", "body-heavy", "calm"],
    traits: ["frosty", "smooth", "terpy"],
    potency: "strong",
  },
  {
    name: "Oreoz",
    aliases: ["Oreo Cookies", "Oreos"],
    type: "hybrid",
    aromas: ["sweet", "earthy", "creamy", "spicy"],
    flavors: ["sweet", "earthy", "creamy", "vanilla"],
    effects: ["relaxed", "euphoric", "body-heavy", "happy", "sleepy"],
    traits: ["frosty", "dense-buds", "sticky", "heavy-body", "potent"],
    potency: "very-strong",
  },
  {
    name: "Lava Cake",
    type: "indica",
    aromas: ["sweet", "earthy", "fruity", "herbal"],
    flavors: ["sweet", "earthy", "fruity"],
    effects: ["relaxed", "body-heavy", "sleepy", "euphoric", "calm"],
    traits: ["smooth", "frosty", "dense-buds"],
    potency: "strong",
  },
  {
    name: "Cake Crasher",
    type: "hybrid",
    aromas: ["sweet", "earthy", "creamy", "herbal"],
    flavors: ["sweet", "earthy", "vanilla", "creamy"],
    effects: ["relaxed", "euphoric", "happy", "body-heavy", "calm"],
    traits: ["frosty", "dense-buds", "sticky", "terpy"],
    potency: "strong",
  },
  {
    name: "LA Kush Cake",
    aliases: ["LAKC"],
    type: "indica",
    aromas: ["sweet", "earthy", "gassy", "vanilla"],
    flavors: ["sweet", "earthy", "vanilla", "creamy"],
    effects: ["relaxed", "body-heavy", "sleepy", "euphoric", "couch-lock"],
    traits: ["frosty", "dense-buds", "heavy-body", "potent", "sticky"],
    potency: "very-strong",
  },
  {
    name: "Sticky Buns",
    type: "hybrid",
    aromas: ["sweet", "creamy", "herbal", "spicy"],
    flavors: ["sweet", "creamy", "vanilla", "nutty"],
    effects: ["relaxed", "euphoric", "happy", "uplifted", "calm"],
    traits: ["frosty", "terpy", "sticky"],
    potency: "strong",
  },
  {
    name: "Pancakes",
    type: "hybrid",
    aromas: ["sweet", "earthy", "creamy", "herbal"],
    flavors: ["sweet", "creamy", "vanilla"],
    effects: ["relaxed", "happy", "euphoric", "uplifted", "calm"],
    traits: ["smooth", "frosty", "terpy"],
    potency: "moderate",
  },
  {
    name: "Birthday Cake",
    aliases: ["Birthday Cake Kush"],
    type: "hybrid",
    aromas: ["sweet", "earthy", "vanilla", "creamy"],
    flavors: ["sweet", "vanilla", "creamy", "earthy"],
    effects: ["relaxed", "happy", "euphoric", "body-heavy", "calm"],
    traits: ["smooth", "dense-buds", "frosty", "terpy"],
    potency: "strong",
  },
  {
    name: "Gelato Cake",
    type: "hybrid",
    aromas: ["sweet", "creamy", "earthy", "vanilla"],
    flavors: ["sweet", "creamy", "vanilla", "earthy"],
    effects: ["relaxed", "euphoric", "body-heavy", "happy", "calm"],
    traits: ["frosty", "sticky", "dense-buds", "potent", "terpy"],
    potency: "very-strong",
  },
  {
    name: "Ice Cream Cake",
    aliases: ["ICC"],
    type: "indica",
    aromas: ["sweet", "creamy", "earthy"],
    flavors: ["sweet", "creamy", "vanilla", "nutty"],
    effects: ["relaxed", "body-heavy", "sleepy", "euphoric", "calm"],
    traits: ["frosty", "dense-buds", "sticky", "heavy-body", "potent"],
    potency: "very-strong",
  },
  {
    name: "Peanut Butter Breath",
    aliases: ["PBB", "PB Breath"],
    type: "hybrid",
    aromas: ["earthy", "woody", "herbal", "sweet"],
    flavors: ["earthy", "woody", "nutty", "herbal"],
    effects: ["relaxed", "euphoric", "body-heavy", "happy", "calm"],
    traits: ["frosty", "dense-buds", "terpy"],
    potency: "strong",
  },
  {
    name: "Grease Monkey",
    type: "hybrid",
    aromas: ["diesel", "earthy", "sweet", "gassy"],
    flavors: ["diesel", "earthy", "sweet"],
    effects: ["relaxed", "body-heavy", "euphoric", "happy", "sleepy"],
    traits: ["frosty", "sticky", "heavy-body", "potent"],
    potency: "very-strong",
  },

  // ── GELATO FAMILY ──
  {
    name: "Gelato",
    aliases: ["Larry Bird"],
    type: "hybrid",
    aromas: ["sweet", "fruity", "berry", "creamy"],
    flavors: ["sweet", "berry", "creamy", "fruity"],
    effects: ["relaxed", "euphoric", "happy", "creative", "calm"],
    traits: ["frosty", "sticky", "terpy", "potent"],
    potency: "strong",
  },
  {
    name: "Gelato 33",
    aliases: ["Gelato #33", "Larry Bird Gelato"],
    type: "hybrid",
    aromas: ["sweet", "fruity", "citrus", "earthy"],
    flavors: ["sweet", "fruity", "creamy", "citrus"],
    effects: ["relaxed", "euphoric", "happy", "creative", "body-heavy"],
    traits: ["frosty", "sticky", "terpy", "potent"],
    potency: "strong",
  },
  {
    name: "Gelato 41",
    aliases: ["Gelato #41", "Bacio Gelato"],
    type: "hybrid",
    aromas: ["sweet", "fruity", "berry", "creamy"],
    flavors: ["sweet", "berry", "creamy", "fruity"],
    effects: ["relaxed", "euphoric", "happy", "calm", "body-heavy"],
    traits: ["frosty", "sticky", "terpy", "potent"],
    potency: "very-strong",
  },
  {
    name: "Lemon Cherry Gelato",
    aliases: ["LCG"],
    type: "hybrid",
    aromas: ["citrus", "berry", "sweet", "creamy", "fruity"],
    flavors: ["citrus", "berry", "sweet", "creamy"],
    effects: ["euphoric", "relaxed", "happy", "calm", "uplifted"],
    traits: ["frosty", "sticky", "loud-smell", "terpy", "potent"],
    potency: "very-strong",
  },
  {
    name: "Sherblato",
    type: "hybrid",
    aromas: ["sweet", "fruity", "citrus", "creamy"],
    flavors: ["sweet", "fruity", "creamy", "citrus"],
    effects: ["euphoric", "happy", "relaxed", "uplifted", "calm"],
    traits: ["frosty", "terpy", "smooth"],
    potency: "strong",
  },
  {
    name: "Peach Gelato",
    type: "hybrid",
    aromas: ["fruity", "sweet", "creamy", "tropical"],
    flavors: ["fruity", "sweet", "creamy", "vanilla"],
    effects: ["relaxed", "happy", "euphoric", "uplifted", "calm"],
    traits: ["smooth", "frosty", "terpy"],
    potency: "strong",
  },
  {
    name: "Italian Ice",
    type: "hybrid",
    aromas: ["sweet", "fruity", "citrus", "tropical"],
    flavors: ["sweet", "fruity", "citrus"],
    effects: ["relaxed", "euphoric", "happy", "uplifted", "calm"],
    traits: ["frosty", "terpy", "smooth"],
    potency: "strong",
  },
  {
    name: "Purple Gelato",
    type: "hybrid",
    aromas: ["sweet", "berry", "fruity", "creamy"],
    flavors: ["sweet", "berry", "creamy", "grape"],
    effects: ["relaxed", "euphoric", "happy", "calm", "body-heavy"],
    traits: ["frosty", "terpy"],
    potency: "strong",
  },

  // ── RUNTZ FAMILY ──
  {
    name: "Runtz",
    aliases: ["White Runtz", "Pink Runtz"],
    type: "hybrid",
    aromas: ["sweet", "fruity", "tropical", "creamy"],
    flavors: ["sweet", "fruity", "creamy", "berry"],
    effects: ["euphoric", "happy", "relaxed", "uplifted", "calm"],
    traits: ["frosty", "sticky", "terpy", "potent"],
    potency: "very-strong",
  },
  {
    name: "Strawberry Runtz",
    type: "hybrid",
    aromas: ["berry", "sweet", "fruity", "creamy"],
    flavors: ["berry", "sweet", "fruity", "creamy"],
    effects: ["euphoric", "happy", "relaxed", "uplifted", "giggly"],
    traits: ["frosty", "terpy", "sticky"],
    potency: "strong",
  },
  {
    name: "Candy Rain",
    type: "hybrid",
    aromas: ["sweet", "fruity", "berry", "tropical"],
    flavors: ["sweet", "fruity", "berry"],
    effects: ["relaxed", "happy", "euphoric", "calm", "uplifted"],
    traits: ["smooth", "terpy", "frosty"],
    potency: "moderate",
  },
  {
    name: "Pink Runtz",
    type: "hybrid",
    aromas: ["sweet", "fruity", "berry", "creamy"],
    flavors: ["sweet", "fruity", "berry"],
    effects: ["euphoric", "relaxed", "happy", "uplifted", "calm"],
    traits: ["frosty", "sticky", "terpy", "potent"],
    potency: "strong",
  },
  {
    name: "Apple Runtz",
    type: "hybrid",
    aromas: ["sweet", "fruity", "tropical", "citrus"],
    flavors: ["sweet", "fruity", "tropical"],
    effects: ["relaxed", "happy", "euphoric", "uplifted"],
    traits: ["frosty", "sticky", "terpy"],
    potency: "strong",
  },
  {
    name: "Obama Runtz",
    type: "indica",
    aromas: ["sweet", "earthy", "berry", "gassy"],
    flavors: ["sweet", "berry", "earthy"],
    effects: ["relaxed", "body-heavy", "calm", "sleepy", "euphoric"],
    traits: ["frosty", "sticky", "heavy-body", "potent"],
    potency: "strong",
  },
  {
    name: "Layer Cake",
    type: "hybrid",
    aromas: ["gassy", "earthy", "sweet", "creamy"],
    flavors: ["earthy", "sweet", "vanilla", "gassy"],
    effects: ["relaxed", "body-heavy", "euphoric", "calm"],
    traits: ["gassy", "sticky", "frosty", "potent", "heavy-body"],
    potency: "very-strong",
    note: "GMO × Wedding Cake — gassy savoury front meets dessert-cake finish.",
  },
  {
    name: "Hippie Crasher",
    type: "hybrid",
    aromas: ["earthy", "sweet", "herbal", "gassy"],
    flavors: ["earthy", "sweet", "herbal", "mint"],
    effects: ["relaxed", "euphoric", "happy", "calm"],
    traits: ["frosty", "sticky", "potent", "terpy"],
    potency: "strong",
  },
  {
    name: "Cherry Lemonade",
    type: "hybrid",
    aromas: ["citrus", "berry", "sweet", "fruity"],
    flavors: ["citrus", "berry", "sweet"],
    effects: ["uplifted", "happy", "euphoric", "energetic"],
    traits: ["terpy", "frosty"],
    potency: "moderate",
  },
  {
    name: "Honey Bun",
    type: "indica",
    aromas: ["sweet", "creamy", "vanilla", "earthy"],
    flavors: ["sweet", "creamy", "vanilla", "nutty"],
    effects: ["relaxed", "euphoric", "happy", "body-heavy"],
    traits: ["frosty", "sticky", "potent", "terpy"],
    potency: "strong",
  },
  {
    name: "Strawberry Shortcake",
    type: "hybrid",
    aromas: ["sweet", "berry", "creamy", "fruity"],
    flavors: ["sweet", "berry", "creamy"],
    effects: ["relaxed", "happy", "euphoric", "uplifted"],
    traits: ["frosty", "sticky", "terpy"],
    potency: "strong",
  },
  {
    name: "Pink Champagne",
    aliases: ["Wedding Cake Champagne"],
    type: "hybrid",
    aromas: ["berry", "sweet", "fruity", "floral"],
    flavors: ["berry", "sweet", "fruity", "grape"],
    effects: ["relaxed", "uplifted", "happy", "euphoric", "calm"],
    traits: ["dense-buds", "terpy", "potent"],
    potency: "strong",
  },

  // ── ZKITTLEZ FAMILY ──
  {
    name: "Zkittlez",
    aliases: ["Skittlez", "Skittles", "Island Zkittlez"],
    type: "indica",
    aromas: ["fruity", "sweet", "berry", "tropical"],
    flavors: ["fruity", "sweet", "berry", "tropical"],
    effects: ["relaxed", "happy", "calm", "euphoric", "uplifted"],
    traits: ["terpy", "frosty", "smooth"],
    potency: "moderate",
  },
  {
    name: "Watermelon Zkittlez",
    aliases: ["Watermelon Z", "Watermelon"],
    type: "indica",
    aromas: ["fruity", "sweet", "tropical", "berry"],
    flavors: ["fruity", "sweet", "tropical", "berry"],
    effects: ["relaxed", "happy", "calm", "euphoric", "body-heavy"],
    traits: ["smooth", "frosty", "terpy"],
    potency: "moderate",
  },
  {
    name: "Grape Gas",
    type: "hybrid",
    aromas: ["berry", "gassy", "sweet", "earthy"],
    flavors: ["grape", "gassy", "sweet", "earthy"],
    effects: ["relaxed", "euphoric", "happy", "body-heavy", "calm"],
    traits: ["gassy", "frosty", "potent", "terpy"],
    potency: "strong",
  },
  {
    name: "Black Cherry Punch",
    type: "indica",
    aromas: ["berry", "sweet", "fruity", "floral"],
    flavors: ["berry", "sweet", "grape", "fruity"],
    effects: ["relaxed", "sleepy", "body-heavy", "euphoric", "calm"],
    traits: ["dense-buds", "heavy-body", "potent", "terpy"],
    potency: "strong",
  },

  // ── MODERN EXOTICS ──
  {
    name: "MAC",
    aliases: ["MAC 1", "Miracle Alien Cookies"],
    type: "hybrid",
    aromas: ["citrus", "sweet", "earthy", "floral", "gassy"],
    flavors: ["citrus", "sweet", "earthy", "creamy"],
    effects: ["euphoric", "happy", "uplifted", "relaxed", "creative"],
    traits: ["frosty", "loud-smell", "potent", "terpy"],
    potency: "very-strong",
  },
  {
    name: "Jealousy",
    type: "hybrid",
    aromas: ["sweet", "earthy", "creamy", "gassy"],
    flavors: ["sweet", "earthy", "creamy"],
    effects: ["relaxed", "euphoric", "happy", "focused", "calm"],
    traits: ["frosty", "sticky", "potent", "terpy"],
    potency: "very-strong",
  },
  {
    name: "Gushers",
    aliases: ["Gusherz"],
    type: "hybrid",
    aromas: ["fruity", "sweet", "tropical", "earthy"],
    flavors: ["fruity", "sweet", "tropical", "creamy"],
    effects: ["relaxed", "euphoric", "happy", "body-heavy", "calm"],
    traits: ["frosty", "sticky", "potent", "terpy"],
    potency: "very-strong",
  },
  {
    name: "Apples and Bananas",
    aliases: ["A&B", "Apples & Bananas"],
    type: "hybrid",
    aromas: ["fruity", "sweet", "tropical", "earthy"],
    flavors: ["fruity", "sweet", "tropical", "creamy"],
    effects: ["relaxed", "euphoric", "happy", "uplifted", "calm"],
    traits: ["frosty", "terpy", "loud-smell"],
    potency: "strong",
  },
  {
    name: "RS11",
    aliases: ["Rainbow Sherbet 11", "Rainbow Sherbet #11"],
    type: "hybrid",
    aromas: ["sweet", "fruity", "citrus", "earthy"],
    flavors: ["sweet", "fruity", "citrus", "creamy"],
    effects: ["euphoric", "happy", "relaxed", "uplifted", "creative"],
    traits: ["frosty", "terpy", "loud-smell", "potent"],
    potency: "very-strong",
  },
  {
    name: "Zoap",
    type: "hybrid",
    aromas: ["floral", "sweet", "fruity", "earthy"],
    flavors: ["sweet", "fruity", "floral", "earthy"],
    effects: ["euphoric", "relaxed", "happy", "uplifted", "focused"],
    traits: ["frosty", "terpy", "dense-buds", "potent"],
    potency: "very-strong",
  },
  {
    name: "Soap",
    aliases: ["Soap #1"],
    type: "hybrid",
    aromas: ["floral", "sweet", "fruity", "earthy"],
    flavors: ["sweet", "fruity", "floral"],
    effects: ["euphoric", "happy", "relaxed", "uplifted", "creative"],
    traits: ["frosty", "terpy", "loud-smell"],
    potency: "strong",
  },
  {
    name: "Sundae Driver",
    type: "hybrid",
    aromas: ["sweet", "creamy", "earthy", "fruity"],
    flavors: ["sweet", "creamy", "vanilla", "earthy"],
    effects: ["relaxed", "happy", "euphoric", "calm", "uplifted"],
    traits: ["smooth", "frosty", "terpy"],
    potency: "moderate",
  },
  {
    name: "Garanimals",
    type: "indica",
    aromas: ["gassy", "earthy", "sweet", "woody"],
    flavors: ["gassy", "earthy", "sweet"],
    effects: ["relaxed", "body-heavy", "euphoric", "sleepy", "couch-lock"],
    traits: ["gassy", "frosty", "heavy-body", "potent"],
    potency: "very-strong",
  },
  {
    name: "Apple Fritter",
    type: "hybrid",
    aromas: ["sweet", "earthy", "fruity", "herbal"],
    flavors: ["sweet", "earthy", "fruity", "vanilla"],
    effects: ["relaxed", "euphoric", "happy", "body-heavy", "calm"],
    traits: ["frosty", "dense-buds", "sticky", "terpy"],
    potency: "very-strong",
  },
  {
    name: "Grape Pie",
    type: "hybrid",
    aromas: ["berry", "sweet", "fruity", "earthy"],
    flavors: ["grape", "berry", "sweet"],
    effects: ["relaxed", "euphoric", "happy", "calm", "body-heavy"],
    traits: ["frosty", "dense-buds", "terpy"],
    potency: "strong",
  },
  {
    name: "Jet Fuel",
    aliases: ["G6", "Jet Fuel OG"],
    type: "hybrid",
    aromas: ["diesel", "gassy", "sweet", "earthy"],
    flavors: ["diesel", "gassy", "sweet"],
    effects: ["energetic", "uplifted", "euphoric", "focused", "happy"],
    traits: ["gassy", "loud-smell", "potent"],
    potency: "strong",
  },
  {
    name: "Space Queen",
    type: "hybrid",
    aromas: ["tropical", "fruity", "sweet", "citrus"],
    flavors: ["tropical", "fruity", "sweet"],
    effects: ["uplifted", "euphoric", "happy", "creative", "energetic"],
    traits: ["terpy", "smooth"],
    potency: "strong",
  },
  {
    name: "Lemon Tree",
    type: "hybrid",
    aromas: ["citrus", "earthy", "sweet", "gassy"],
    flavors: ["citrus", "earthy", "sweet"],
    effects: ["relaxed", "euphoric", "happy", "focused", "uplifted"],
    traits: ["frosty", "loud-smell", "terpy"],
    potency: "strong",
  },
  {
    name: "Melonade",
    type: "sativa",
    aromas: ["citrus", "tropical", "sweet", "fruity"],
    flavors: ["citrus", "tropical", "sweet"],
    effects: ["uplifted", "energetic", "happy", "euphoric", "creative"],
    traits: ["terpy", "loud-smell"],
    potency: "moderate",
  },
  {
    name: "Cap Junky",
    aliases: ["Cap Junkie"],
    type: "hybrid",
    aromas: ["gassy", "earthy", "herbal", "citrus"],
    flavors: ["gassy", "earthy", "citrus", "herbal"],
    effects: ["euphoric", "happy", "energetic", "uplifted", "head-high"],
    traits: ["frosty", "gassy", "loud-smell", "potent", "terpy"],
    potency: "very-strong",
    note: "Modern OG-and-cookies bx — heavy on the front, loud nose, potent enough that one bowl tells you.",
  },
  {
    name: "Black Truffle",
    type: "hybrid",
    aromas: ["gassy", "earthy", "woody", "herbal"],
    flavors: ["gassy", "earthy", "nutty", "herbal"],
    effects: ["relaxed", "body-heavy", "euphoric", "calm", "sleepy"],
    traits: ["gassy", "sticky", "frosty", "heavy-body", "potent"],
    potency: "very-strong",
    note: "PB-and-gas crossover from the Seed Junky family. Savoury finish, heavy body.",
  },
  {
    name: "Frosted Lemonade",
    type: "hybrid",
    aromas: ["citrus", "sweet", "creamy", "berry"],
    flavors: ["citrus", "sweet", "creamy", "vanilla"],
    effects: ["uplifted", "euphoric", "happy", "relaxed"],
    traits: ["frosty", "terpy", "potent", "sticky"],
    potency: "strong",
  },
  {
    name: "Sherbanger",
    type: "hybrid",
    aromas: ["sweet", "citrus", "gassy", "fruity"],
    flavors: ["sweet", "citrus", "fruity", "creamy"],
    effects: ["euphoric", "uplifted", "happy", "head-high", "energetic"],
    traits: ["terpy", "frosty", "potent"],
    potency: "strong",
  },
  {
    name: "Triangle Mints",
    type: "hybrid",
    aromas: ["earthy", "herbal", "gassy", "spicy"],
    flavors: ["earthy", "herbal", "mint", "gassy"],
    effects: ["relaxed", "euphoric", "happy", "calm", "body-heavy"],
    traits: ["gassy", "frosty", "sticky", "potent", "terpy"],
    potency: "strong",
    note: "Parent of Permanent Marker — minty kush backbone with cookies-class frost.",
  },
  {
    name: "Lemonatti",
    type: "hybrid",
    aromas: ["citrus", "sweet", "earthy", "herbal"],
    flavors: ["citrus", "sweet", "herbal", "earthy"],
    effects: ["relaxed", "happy", "euphoric", "uplifted"],
    traits: ["terpy", "frosty", "sticky", "potent"],
    potency: "strong",
  },

  // ── FRUITY / TROPICAL ──
  {
    name: "Pineapple Express",
    type: "hybrid",
    aromas: ["tropical", "fruity", "sweet", "citrus", "pine"],
    flavors: ["tropical", "fruity", "sweet", "citrus"],
    effects: ["uplifted", "happy", "energetic", "creative", "relaxed"],
    traits: ["smooth", "terpy"],
    potency: "moderate",
  },
  {
    name: "Mimosa",
    type: "hybrid",
    aromas: ["citrus", "fruity", "sweet", "tropical"],
    flavors: ["citrus", "fruity", "sweet", "tropical"],
    effects: ["uplifted", "energetic", "happy", "focused", "euphoric"],
    traits: ["terpy", "loud-smell"],
    potency: "strong",
  },
  {
    name: "Blue Dream",
    type: "hybrid",
    aromas: ["berry", "sweet", "herbal", "fruity"],
    flavors: ["berry", "sweet", "fruity"],
    effects: ["happy", "uplifted", "relaxed", "creative", "calm"],
    traits: ["smooth", "terpy"],
    potency: "moderate",
  },
  {
    name: "Strawberry Banana",
    aliases: ["Strawnana", "SB"],
    type: "indica",
    aromas: ["fruity", "sweet", "tropical", "berry"],
    flavors: ["fruity", "sweet", "berry", "tropical"],
    effects: ["relaxed", "happy", "euphoric", "calm", "body-heavy"],
    traits: ["smooth", "terpy", "frosty"],
    potency: "strong",
  },
  {
    name: "Banana Kush",
    aliases: ["Banana"],
    type: "indica",
    aromas: ["sweet", "tropical", "fruity", "earthy"],
    flavors: ["sweet", "tropical", "fruity", "vanilla"],
    effects: ["relaxed", "body-heavy", "happy", "sleepy", "euphoric"],
    traits: ["smooth", "dense-buds", "terpy"],
    potency: "strong",
  },
  {
    name: "Mango Kush",
    aliases: ["Mango"],
    type: "indica",
    aromas: ["tropical", "fruity", "sweet", "earthy"],
    flavors: ["tropical", "fruity", "sweet"],
    effects: ["relaxed", "happy", "body-heavy", "calm", "euphoric"],
    traits: ["smooth", "terpy"],
    potency: "moderate",
  },
  {
    name: "Banana OG",
    type: "indica",
    aromas: ["sweet", "tropical", "earthy", "fruity"],
    flavors: ["sweet", "tropical", "earthy", "vanilla"],
    effects: ["relaxed", "body-heavy", "sleepy", "happy", "calm"],
    traits: ["heavy-body", "smooth", "dense-buds"],
    potency: "strong",
  },
  {
    name: "Banana Punch",
    type: "hybrid",
    aromas: ["sweet", "tropical", "fruity", "berry"],
    flavors: ["sweet", "tropical", "fruity", "vanilla"],
    effects: ["relaxed", "happy", "euphoric", "uplifted", "calm"],
    traits: ["smooth", "terpy"],
    potency: "strong",
  },
  {
    name: "Papaya",
    aliases: ["Papaya Cake"],
    type: "indica",
    aromas: ["tropical", "fruity", "sweet", "earthy"],
    flavors: ["tropical", "fruity", "sweet"],
    effects: ["relaxed", "body-heavy", "happy", "calm", "sleepy"],
    traits: ["dense-buds", "smooth", "terpy"],
    potency: "moderate",
  },
  {
    name: "Peach Rings",
    aliases: ["Peach"],
    type: "hybrid",
    aromas: ["fruity", "sweet", "tropical", "citrus"],
    flavors: ["fruity", "sweet", "tropical"],
    effects: ["relaxed", "happy", "uplifted", "calm", "euphoric"],
    traits: ["smooth", "terpy"],
    potency: "moderate",
  },
  {
    name: "Passion Fruit",
    type: "hybrid",
    aromas: ["tropical", "fruity", "sweet", "floral"],
    flavors: ["tropical", "fruity", "sweet"],
    effects: ["relaxed", "happy", "uplifted", "calm", "euphoric"],
    traits: ["smooth", "terpy"],
    potency: "moderate",
  },
  {
    name: "Forbidden Fruit",
    type: "indica",
    aromas: ["fruity", "tropical", "berry", "citrus", "pine"],
    flavors: ["fruity", "tropical", "berry", "citrus"],
    effects: ["relaxed", "body-heavy", "happy", "sleepy", "calm"],
    traits: ["frosty", "dense-buds", "smooth", "terpy"],
    potency: "strong",
  },
  {
    name: "Tangie",
    type: "sativa",
    aromas: ["citrus", "sweet", "tropical", "herbal"],
    flavors: ["citrus", "sweet", "tropical"],
    effects: ["uplifted", "energetic", "happy", "creative", "focused"],
    traits: ["loud-smell", "terpy"],
    potency: "strong",
  },
  {
    name: "Tropicana Cookies",
    aliases: ["Tropicana", "Trops"],
    type: "sativa",
    aromas: ["citrus", "sweet", "fruity", "tropical"],
    flavors: ["citrus", "sweet", "fruity", "tropical"],
    effects: ["uplifted", "happy", "energetic", "euphoric", "creative"],
    traits: ["frosty", "terpy", "loud-smell"],
    potency: "strong",
  },
  {
    name: "Tropicana Cherry",
    type: "hybrid",
    aromas: ["citrus", "berry", "sweet", "tropical"],
    flavors: ["citrus", "berry", "sweet"],
    effects: ["uplifted", "happy", "euphoric", "energetic", "creative"],
    traits: ["frosty", "terpy", "loud-smell"],
    potency: "strong",
  },
  {
    name: "Orange Creamsicle",
    aliases: ["Creamsicle"],
    type: "hybrid",
    aromas: ["citrus", "sweet", "creamy", "tropical"],
    flavors: ["citrus", "sweet", "creamy", "vanilla"],
    effects: ["uplifted", "happy", "relaxed", "euphoric", "calm"],
    traits: ["smooth", "terpy"],
    potency: "moderate",
  },
  {
    name: "Pink Lemonade",
    type: "sativa",
    aromas: ["citrus", "berry", "sweet", "fruity"],
    flavors: ["citrus", "berry", "sweet"],
    effects: ["uplifted", "happy", "energetic", "euphoric", "creative"],
    traits: ["terpy", "loud-smell"],
    potency: "moderate",
  },
  {
    name: "Blueberry Muffin",
    type: "hybrid",
    aromas: ["berry", "sweet", "creamy", "earthy"],
    flavors: ["berry", "sweet", "creamy", "vanilla"],
    effects: ["relaxed", "happy", "euphoric", "calm", "uplifted"],
    traits: ["smooth", "frosty", "terpy"],
    potency: "moderate",
  },
  {
    name: "Blueberry Cupcake",
    type: "hybrid",
    aromas: ["berry", "sweet", "creamy", "fruity"],
    flavors: ["berry", "sweet", "creamy", "vanilla"],
    effects: ["relaxed", "happy", "euphoric", "calm", "body-heavy"],
    traits: ["smooth", "frosty", "terpy"],
    potency: "moderate",
  },
  {
    name: "White Hot Guava",
    aliases: ["Hot Guava", "WHG"],
    type: "hybrid",
    aromas: ["tropical", "fruity", "sweet", "gassy"],
    flavors: ["tropical", "fruity", "sweet", "gassy"],
    effects: ["relaxed", "euphoric", "happy", "calm", "body-heavy"],
    traits: ["frosty", "sticky", "loud-smell", "terpy", "potent"],
    potency: "strong",
    note: "Guava-forward gas hybrid — fruity nose over a sticky, resinous body.",
  },

  // ── CITRUS / HAZE SATIVAS ──
  {
    name: "Super Lemon Haze",
    aliases: ["SLH"],
    type: "sativa",
    aromas: ["citrus", "sweet", "herbal"],
    flavors: ["citrus", "sweet", "herbal"],
    effects: ["uplifted", "energetic", "happy", "creative", "head-high"],
    traits: ["loud-smell", "terpy"],
    potency: "strong",
  },
  {
    name: "Lemon Haze",
    type: "sativa",
    aromas: ["citrus", "sweet", "earthy"],
    flavors: ["citrus", "sweet"],
    effects: ["uplifted", "energetic", "happy", "focused", "creative"],
    traits: ["loud-smell", "terpy"],
    potency: "moderate",
  },
  {
    name: "Amnesia Haze",
    aliases: ["Amnesia"],
    type: "sativa",
    aromas: ["citrus", "earthy", "spicy", "herbal"],
    flavors: ["citrus", "earthy", "herbal"],
    effects: ["uplifted", "energetic", "happy", "creative", "head-high"],
    traits: ["loud-smell", "terpy"],
    potency: "strong",
  },
  {
    name: "Super Silver Haze",
    aliases: ["SSH"],
    type: "sativa",
    aromas: ["citrus", "earthy", "spicy", "herbal"],
    flavors: ["citrus", "earthy", "spicy", "herbal"],
    effects: ["uplifted", "energetic", "happy", "focused", "head-high"],
    traits: ["loud-smell", "terpy"],
    potency: "strong",
  },
  {
    name: "Ghost Train Haze",
    aliases: ["GTH"],
    type: "sativa",
    aromas: ["citrus", "floral", "earthy", "pine"],
    flavors: ["citrus", "earthy", "pine"],
    effects: ["uplifted", "energetic", "focused", "creative", "head-high"],
    traits: ["loud-smell", "frosty", "potent"],
    potency: "very-strong",
  },
  {
    name: "Clementine",
    type: "sativa",
    aromas: ["citrus", "sweet", "herbal"],
    flavors: ["citrus", "sweet"],
    effects: ["uplifted", "energetic", "focused", "happy", "creative"],
    traits: ["terpy", "loud-smell"],
    potency: "moderate",
  },
  {
    name: "Cinex",
    type: "sativa",
    aromas: ["citrus", "sweet", "earthy"],
    flavors: ["citrus", "sweet"],
    effects: ["uplifted", "energetic", "focused", "happy", "creative"],
    traits: ["terpy", "dense-buds"],
    potency: "moderate",
  },
  {
    name: "Sour Apple",
    type: "hybrid",
    aromas: ["citrus", "sweet", "diesel", "fruity"],
    flavors: ["citrus", "sweet", "fruity"],
    effects: ["uplifted", "happy", "euphoric", "energetic"],
    traits: ["terpy", "loud-smell"],
    potency: "moderate",
  },
  {
    name: "Tangie Banana",
    type: "hybrid",
    aromas: ["citrus", "tropical", "sweet", "fruity"],
    flavors: ["citrus", "tropical", "sweet", "fruity"],
    effects: ["uplifted", "happy", "euphoric", "energetic", "creative"],
    traits: ["terpy", "frosty"],
    potency: "moderate",
  },
  {
    name: "Lemon Tek",
    type: "hybrid",
    aromas: ["citrus", "gassy", "skunky", "sweet"],
    flavors: ["citrus", "sweet", "gassy"],
    effects: ["uplifted", "energetic", "happy", "focused", "euphoric"],
    traits: ["terpy", "loud-smell", "potent"],
    potency: "strong",
  },

  // ── CLASSIC SATIVAS ──
  {
    name: "Jack Herer",
    aliases: ["JH", "The Jack"],
    type: "sativa",
    aromas: ["pine", "spicy", "earthy", "herbal", "citrus"],
    flavors: ["pine", "spicy", "citrus", "herbal"],
    effects: ["uplifted", "focused", "creative", "energetic", "happy"],
    traits: ["terpy", "loud-smell"],
    potency: "strong",
  },
  {
    name: "Durban Poison",
    aliases: ["Durban"],
    type: "sativa",
    aromas: ["pine", "spicy", "sweet", "earthy"],
    flavors: ["pine", "spicy", "sweet", "herbal"],
    effects: ["energetic", "focused", "uplifted", "creative", "happy"],
    traits: ["terpy", "dense-buds"],
    potency: "strong",
  },
  {
    name: "Green Crack",
    aliases: ["Green Cush"],
    type: "sativa",
    aromas: ["citrus", "fruity", "tropical", "earthy"],
    flavors: ["citrus", "fruity", "tropical"],
    effects: ["energetic", "focused", "uplifted", "happy", "head-high"],
    traits: ["loud-smell", "terpy"],
    potency: "strong",
  },
  {
    name: "Trainwreck",
    type: "hybrid",
    aromas: ["pine", "citrus", "spicy", "earthy"],
    flavors: ["pine", "citrus", "spicy", "earthy"],
    effects: ["euphoric", "uplifted", "energetic", "happy", "creative"],
    traits: ["loud-smell", "terpy"],
    potency: "strong",
  },
  {
    name: "Bruce Banner",
    aliases: ["Banner", "Bruce Banner #3"],
    type: "hybrid",
    aromas: ["diesel", "gassy", "sweet", "earthy"],
    flavors: ["diesel", "sweet", "earthy"],
    effects: ["euphoric", "energetic", "happy", "uplifted", "creative"],
    traits: ["gassy", "loud-smell", "potent", "frosty"],
    potency: "very-strong",
  },
  {
    name: "AK-47",
    aliases: ["AK47", "AK"],
    type: "hybrid",
    aromas: ["earthy", "floral", "woody", "spicy"],
    flavors: ["earthy", "woody", "floral", "spicy"],
    effects: ["uplifted", "happy", "relaxed", "creative", "calm"],
    traits: ["loud-smell", "terpy"],
    potency: "strong",
  },
  {
    name: "Strawberry Cough",
    aliases: ["Strawberry"],
    type: "sativa",
    aromas: ["berry", "sweet", "fruity", "herbal"],
    flavors: ["berry", "sweet", "fruity"],
    effects: ["uplifted", "happy", "energetic", "focused", "creative"],
    traits: ["smooth", "terpy"],
    potency: "moderate",
  },
  {
    name: "Maui Wowie",
    aliases: ["Maui Waui", "Maui"],
    type: "sativa",
    aromas: ["tropical", "sweet", "citrus", "fruity"],
    flavors: ["tropical", "sweet", "citrus", "fruity"],
    effects: ["uplifted", "energetic", "happy", "creative", "euphoric"],
    traits: ["smooth", "terpy"],
    potency: "moderate",
  },
  {
    name: "Chocolope",
    aliases: ["Choco Haze"],
    type: "sativa",
    aromas: ["earthy", "sweet", "herbal", "woody"],
    flavors: ["earthy", "sweet", "woody", "nutty"],
    effects: ["uplifted", "energetic", "happy", "focused", "creative"],
    traits: ["terpy", "well-cured"],
    potency: "strong",
  },
  {
    name: "Acapulco Gold",
    type: "sativa",
    aromas: ["earthy", "sweet", "woody", "spicy"],
    flavors: ["earthy", "sweet", "woody"],
    effects: ["uplifted", "energetic", "euphoric", "happy", "creative"],
    traits: ["smooth", "well-cured"],
    potency: "moderate",
  },
  {
    name: "Moby Dick",
    type: "sativa",
    aromas: ["citrus", "earthy", "herbal", "vanilla"],
    flavors: ["citrus", "earthy", "vanilla"],
    effects: ["uplifted", "energetic", "euphoric", "focused", "creative"],
    traits: ["loud-smell", "frosty"],
    potency: "strong",
  },
  {
    name: "Candyland",
    type: "sativa",
    aromas: ["sweet", "spicy", "earthy", "herbal"],
    flavors: ["sweet", "spicy", "earthy"],
    effects: ["uplifted", "happy", "focused", "energetic", "creative"],
    traits: ["terpy", "dense-buds"],
    potency: "moderate",
  },
  {
    name: "Bay 11",
    type: "sativa",
    aromas: ["pine", "herbal", "spicy", "citrus"],
    flavors: ["pine", "herbal", "citrus"],
    effects: ["uplifted", "energetic", "happy", "focused", "head-high"],
    traits: ["terpy", "dense-buds"],
    potency: "strong",
  },

  // ── SKUNK / CHEESE ──
  {
    name: "Skunk #1",
    aliases: ["Skunk", "Original Skunk"],
    type: "hybrid",
    aromas: ["skunky", "earthy", "sweet", "spicy"],
    flavors: ["earthy", "sweet", "spicy"],
    effects: ["uplifted", "happy", "relaxed", "creative", "hungry"],
    traits: ["loud-smell", "earthy"],
    potency: "moderate",
  },
  {
    name: "Super Skunk",
    type: "indica",
    aromas: ["skunky", "earthy", "spicy", "sweet"],
    flavors: ["earthy", "sweet", "spicy"],
    effects: ["relaxed", "happy", "body-heavy", "hungry", "calm"],
    traits: ["loud-smell", "earthy", "heavy-body"],
    potency: "moderate",
  },
  {
    name: "Lemon Skunk",
    type: "hybrid",
    aromas: ["citrus", "skunky", "earthy", "sweet"],
    flavors: ["citrus", "sweet", "earthy"],
    effects: ["uplifted", "happy", "energetic", "euphoric", "creative"],
    traits: ["loud-smell", "terpy"],
    potency: "moderate",
  },
  {
    name: "NYC Diesel",
    aliases: ["New York Diesel", "NY Diesel"],
    type: "sativa",
    aromas: ["diesel", "citrus", "gassy", "skunky"],
    flavors: ["diesel", "citrus", "gassy"],
    effects: ["energetic", "uplifted", "euphoric", "focused", "creative"],
    traits: ["gassy", "loud-smell", "terpy"],
    potency: "strong",
  },
  {
    name: "Stardawg",
    aliases: ["Stardawg Guava"],
    type: "hybrid",
    aromas: ["diesel", "gassy", "earthy", "pine"],
    flavors: ["diesel", "earthy", "pine"],
    effects: ["euphoric", "uplifted", "relaxed", "happy", "creative"],
    traits: ["gassy", "loud-smell", "frosty", "sticky"],
    potency: "strong",
  },
  {
    name: "UK Cheese",
    aliases: ["Cheese", "Original Cheese"],
    type: "hybrid",
    aromas: ["cheese", "earthy", "skunky", "sweet"],
    flavors: ["cheese", "earthy", "sweet"],
    effects: ["relaxed", "happy", "euphoric", "uplifted", "body-heavy"],
    traits: ["loud-smell", "earthy"],
    potency: "moderate",
  },
  {
    name: "Blue Cheese",
    type: "indica",
    aromas: ["cheese", "berry", "earthy", "sweet"],
    flavors: ["cheese", "berry", "sweet"],
    effects: ["relaxed", "body-heavy", "happy", "sleepy", "calm"],
    traits: ["heavy-body", "smooth"],
    potency: "moderate",
  },

  // ── WHITE / FROSTY ──
  {
    name: "White Widow",
    type: "hybrid",
    aromas: ["earthy", "woody", "pine", "spicy"],
    flavors: ["earthy", "woody", "herbal"],
    effects: ["euphoric", "uplifted", "energetic", "happy", "creative"],
    traits: ["frosty", "loud-smell"],
    potency: "strong",
  },
  {
    name: "White Runtz",
    type: "hybrid",
    aromas: ["sweet", "fruity", "creamy", "tropical"],
    flavors: ["sweet", "fruity", "creamy"],
    effects: ["euphoric", "relaxed", "happy", "uplifted", "calm"],
    traits: ["frosty", "sticky", "potent", "terpy"],
    potency: "very-strong",
    note: "Frostier, creamier phenotype of Runtz.",
  },

  // ── ADDITIONAL COMMONS ──
  {
    name: "Lemon Pound Cake",
    type: "hybrid",
    aromas: ["citrus", "sweet", "creamy", "earthy"],
    flavors: ["citrus", "sweet", "creamy", "vanilla"],
    effects: ["relaxed", "happy", "euphoric", "uplifted", "calm"],
    traits: ["smooth", "terpy", "frosty"],
    potency: "moderate",
  },
  {
    name: "MAC and Cheese",
    aliases: ["Mac N Cheese"],
    type: "hybrid",
    aromas: ["cheese", "citrus", "sweet", "earthy"],
    flavors: ["cheese", "citrus", "sweet"],
    effects: ["euphoric", "relaxed", "happy", "uplifted", "creative"],
    traits: ["frosty", "terpy", "potent"],
    potency: "very-strong",
  },
  {
    name: "Grape Stomper",
    aliases: ["Sour Grapes"],
    type: "hybrid",
    aromas: ["berry", "sweet", "gassy", "fruity"],
    flavors: ["grape", "berry", "sweet"],
    effects: ["uplifted", "euphoric", "happy", "relaxed", "creative"],
    traits: ["frosty", "terpy"],
    potency: "strong",
  },
  {
    name: "Cotton Candy Kush",
    aliases: ["Cotton Candy"],
    type: "hybrid",
    aromas: ["sweet", "fruity", "floral", "creamy"],
    flavors: ["sweet", "fruity", "vanilla", "creamy"],
    effects: ["relaxed", "happy", "euphoric", "uplifted", "giggly"],
    traits: ["smooth", "terpy"],
    potency: "moderate",
  },
  {
    name: "Orange Bud",
    type: "hybrid",
    aromas: ["citrus", "sweet", "earthy", "spicy"],
    flavors: ["citrus", "sweet", "earthy"],
    effects: ["uplifted", "happy", "energetic", "creative", "euphoric"],
    traits: ["terpy", "loud-smell"],
    potency: "moderate",
  },
  {
    name: "Sour Tangie",
    type: "sativa",
    aromas: ["citrus", "diesel", "earthy", "sweet"],
    flavors: ["citrus", "diesel", "sweet"],
    effects: ["uplifted", "energetic", "happy", "creative", "focused"],
    traits: ["loud-smell", "terpy"],
    potency: "strong",
  },
  {
    name: "Platinum Kush",
    aliases: ["Platinum OG Kush"],
    type: "indica",
    aromas: ["gassy", "earthy", "spicy", "herbal"],
    flavors: ["earthy", "gassy", "herbal"],
    effects: ["relaxed", "sleepy", "body-heavy", "couch-lock", "euphoric"],
    traits: ["frosty", "heavy-body", "dense-buds", "potent"],
    potency: "very-strong",
  },
  {
    name: "Hash Plant",
    aliases: ["HP"],
    type: "indica",
    aromas: ["earthy", "woody", "spicy", "herbal"],
    flavors: ["earthy", "woody", "herbal"],
    effects: ["relaxed", "body-heavy", "sleepy", "couch-lock", "calm"],
    traits: ["earthy", "smooth", "heavy-body", "dense-buds"],
    potency: "strong",
  },
  {
    name: "Cheetah Piss",
    type: "hybrid",
    aromas: ["gassy", "sweet", "earthy", "diesel"],
    flavors: ["gassy", "sweet", "earthy"],
    effects: ["euphoric", "uplifted", "happy", "energetic", "creative"],
    traits: ["gassy", "loud-smell", "frosty", "potent"],
    potency: "very-strong",
  },

  // ── ROUND 4: NEW 2024–2026 DISPENSARY RELEASES ──
  {
    name: "White Truffle",
    aliases: ["WT", "White Truffle Gelato"],
    type: "hybrid",
    aromas: ["earthy", "gassy", "woody", "herbal"],
    flavors: ["earthy", "gassy", "nutty", "woody"],
    effects: ["relaxed", "euphoric", "body-heavy", "happy", "sleepy"],
    traits: ["frosty", "potent", "sticky", "loud-smell", "dense-buds"],
    potency: "strong",
    note: "Gorilla Butter phenotype — savoury truffle-and-gas nose, heavy indica-leaning body.",
  },
  {
    name: "Animal Face",
    aliases: ["Animal Face #10"],
    type: "hybrid",
    aromas: ["gassy", "pine", "sweet", "earthy"],
    flavors: ["gassy", "pine", "sweet", "earthy"],
    effects: ["euphoric", "happy", "relaxed", "uplifted", "creative"],
    traits: ["frosty", "potent", "loud-smell", "terpy"],
    potency: "very-strong",
    note: "Face Off OG's piney fuel over Animal Mints cookies — frosty and very potent.",
  },
  {
    name: "Project 4516",
    aliases: ["4516"],
    type: "hybrid",
    aromas: ["sweet", "gassy", "berry", "earthy"],
    flavors: ["sweet", "creamy", "berry", "gassy"],
    effects: ["relaxed", "euphoric", "happy", "body-heavy", "uplifted"],
    traits: ["frosty", "potent", "dense-buds", "terpy"],
    potency: "very-strong",
    note: "Creamy gelato over earthy gas — Grandiflora's heavy, frosty hybrid.",
  },
  {
    name: "Modified Grapes",
    aliases: ["Modified Grape"],
    type: "indica",
    aromas: ["gassy", "earthy", "berry", "spicy"],
    flavors: ["gassy", "grape", "earthy", "berry"],
    effects: ["relaxed", "euphoric", "body-heavy", "happy", "sleepy"],
    traits: ["frosty", "potent", "loud-smell", "heavy-body"],
    potency: "very-strong",
    note: "GMO's garlic-gas funk fused with Purple Punch grape — pungent and heavy.",
  },
  {
    name: "Snowman",
    aliases: ["Snowman Cookies"],
    type: "hybrid",
    aromas: ["sweet", "earthy", "vanilla", "pine"],
    flavors: ["sweet", "vanilla", "earthy", "pine"],
    effects: ["euphoric", "happy", "relaxed", "uplifted", "creative"],
    traits: ["frosty", "potent", "dense-buds", "terpy"],
    potency: "strong",
    note: "Frosty GSC phenotype — sweet vanilla-cookie nose, balanced euphoric high.",
  },
  {
    name: "The White",
    aliases: ["Triangle", "The White Triangle"],
    type: "hybrid",
    aromas: ["earthy", "woody", "pine", "herbal"],
    flavors: ["earthy", "woody", "herbal", "pine"],
    effects: ["relaxed", "euphoric", "body-heavy", "happy", "sleepy"],
    traits: ["frosty", "potent", "dense-buds", "sticky"],
    potency: "strong",
    note: "Florida clone-only — trichome-white frost and an unusually faint nose.",
  },
  {
    name: "Sherb Crasher",
    type: "hybrid",
    aromas: ["sweet", "creamy", "berry", "gassy"],
    flavors: ["sweet", "creamy", "berry", "grape"],
    effects: ["relaxed", "euphoric", "happy", "body-heavy", "calm"],
    traits: ["frosty", "potent", "dense-buds", "terpy"],
    potency: "strong",
    note: "Sunset Sherbet cream crossed into Wedding Crasher grape-gas — frosty dessert hybrid.",
  },
  {
    name: "E85",
    type: "hybrid",
    aromas: ["gassy", "sweet", "earthy", "diesel"],
    flavors: ["gassy", "sweet", "creamy", "diesel"],
    effects: ["euphoric", "relaxed", "happy", "uplifted", "body-heavy"],
    traits: ["frosty", "potent", "loud-smell", "terpy"],
    potency: "very-strong",
    note: "Grandiflora's gassy dessert — Wedding Cake sweetness over fuel.",
  },
  {
    name: "Sundae Sherbert",
    type: "hybrid",
    aromas: ["sweet", "creamy", "fruity", "pine"],
    flavors: ["sweet", "creamy", "fruity", "grape"],
    effects: ["relaxed", "happy", "euphoric", "calm", "uplifted"],
    traits: ["frosty", "smooth", "terpy", "potent"],
    potency: "strong",
    note: "Sundae Driver smoothness meets Sunset Sherbet citrus — creamy, balanced.",
  },
  {
    name: "Cherry MAC",
    aliases: ["Cherry MAC Pie"],
    type: "hybrid",
    aromas: ["sweet", "fruity", "gassy", "floral"],
    flavors: ["sweet", "fruity", "berry", "gassy"],
    effects: ["euphoric", "happy", "relaxed", "uplifted", "creative"],
    traits: ["frosty", "potent", "terpy"],
    potency: "strong",
    note: "MAC's diesel funk softened with cherry fruit — frosty and balanced.",
  },
  {
    name: "Studio 54",
    type: "hybrid",
    aromas: ["sweet", "fruity", "tropical", "gassy"],
    flavors: ["sweet", "tropical", "fruity", "creamy"],
    effects: ["euphoric", "relaxed", "happy", "uplifted", "calm"],
    traits: ["frosty", "potent", "terpy", "dense-buds"],
    potency: "strong",
    note: "Doja/Deep East exotic — guava-sherbet sweetness, RS11's sibling cut.",
  },
  {
    name: "Pink Picasso",
    type: "hybrid",
    aromas: ["sweet", "fruity", "berry", "floral"],
    flavors: ["sweet", "fruity", "berry", "grape"],
    effects: ["euphoric", "happy", "relaxed", "uplifted", "creative"],
    traits: ["frosty", "potent", "terpy"],
    potency: "strong",
    note: "Wonderbrett candy-grape exotic — colourful, dessert-forward, resin-heavy.",
  },
  {
    name: "Power Sherbet",
    aliases: ["Power Sherb"],
    type: "indica",
    aromas: ["sweet", "creamy", "earthy", "gassy"],
    flavors: ["sweet", "creamy", "nutty", "earthy"],
    effects: ["relaxed", "body-heavy", "euphoric", "happy", "sleepy"],
    traits: ["frosty", "potent", "heavy-body", "dense-buds"],
    potency: "strong",
    note: "Exotic Genetix indica — Sunset Sherbet cream over Cookies & Cream weight.",
  },
  {
    name: "High Octane OG",
    aliases: ["Hi-Octane OG", "Octane", "Heirloom OG"],
    type: "indica",
    aromas: ["gassy", "earthy", "pine", "diesel"],
    flavors: ["gassy", "earthy", "pine", "diesel"],
    effects: ["relaxed", "body-heavy", "sleepy", "euphoric", "couch-lock"],
    traits: ["gassy", "potent", "dense-buds", "loud-smell", "heavy-body"],
    potency: "very-strong",
    note: "Clone-only OG — heavy fuel-and-pine, deeply sedating nightcap.",
  },
  {
    name: "Cherry Cake",
    aliases: ["Cherry Cake OG"],
    type: "hybrid",
    aromas: ["sweet", "fruity", "earthy", "berry"],
    flavors: ["sweet", "fruity", "berry", "vanilla"],
    effects: ["relaxed", "euphoric", "happy", "calm", "uplifted"],
    traits: ["frosty", "terpy", "potent"],
    potency: "strong",
    note: "Cherry fruit on a cake-sweet base — name spans several regional cuts.",
  },
  {
    name: "Hot Sauce",
    type: "hybrid",
    aromas: ["gassy", "spicy", "earthy", "herbal"],
    flavors: ["gassy", "spicy", "earthy", "herbal"],
    effects: ["relaxed", "euphoric", "body-heavy", "happy", "sleepy"],
    traits: ["frosty", "potent", "loud-smell", "heavy-body"],
    potency: "very-strong",
    note: "In House's Chile Verde × Pancakes — gassy, spicy and heavy.",
  },
  {
    name: "Orange Daiquiri",
    type: "hybrid",
    aromas: ["citrus", "sweet", "fruity", "pine"],
    flavors: ["citrus", "sweet", "fruity", "tropical"],
    effects: ["uplifted", "happy", "euphoric", "energetic", "creative"],
    traits: ["terpy", "frosty", "potent"],
    potency: "strong",
    note: "Cannarado citrus dessert — sweet orange over a piney, gassy backbone.",
  },
  {
    name: "Georgia Pie",
    type: "hybrid",
    aromas: ["sweet", "fruity", "earthy", "creamy"],
    flavors: ["sweet", "fruity", "creamy", "nutty"],
    effects: ["relaxed", "euphoric", "happy", "body-heavy", "calm"],
    traits: ["frosty", "potent", "terpy", "dense-buds"],
    potency: "strong",
    note: "Seed Junky peach-cobbler dessert — sweet stone-fruit over cookie cream.",
  },
  {
    name: "Rainbow Belts",
    type: "hybrid",
    aromas: ["sweet", "fruity", "berry", "tropical"],
    flavors: ["sweet", "fruity", "berry", "grape"],
    effects: ["euphoric", "happy", "relaxed", "uplifted", "giggly"],
    traits: ["frosty", "potent", "terpy"],
    potency: "strong",
    note: "Archive candy exotic — Zkittlez berry over Moonbow, colourful and sweet.",
  },
  {
    name: "Khalifa Kush",
    aliases: ["KK", "Wiz Khalifa OG"],
    type: "indica",
    aromas: ["gassy", "pine", "earthy", "citrus"],
    flavors: ["gassy", "pine", "earthy", "citrus"],
    effects: ["relaxed", "euphoric", "happy", "body-heavy", "uplifted"],
    traits: ["gassy", "potent", "dense-buds", "frosty"],
    potency: "very-strong",
    note: "Wiz Khalifa's OG Kush cut — sharp lemon-pine gas, heavy and potent.",
  },

  // ── ROUND 5: PARENT-LINE FILL + MORE 2024–2026 RELEASES ──
  {
    name: "Wedding Crasher",
    type: "hybrid",
    aromas: ["sweet", "fruity", "earthy", "vanilla"],
    flavors: ["sweet", "grape", "vanilla", "fruity"],
    effects: ["uplifted", "euphoric", "happy", "relaxed", "creative"],
    traits: ["frosty", "terpy", "potent"],
    potency: "strong",
    note: "Wedding Cake vanilla over Purple Punch grape — bright, uplifting hybrid.",
  },
  {
    name: "Gelatti",
    type: "hybrid",
    aromas: ["sweet", "gassy", "earthy", "creamy"],
    flavors: ["sweet", "creamy", "gassy", "earthy"],
    effects: ["relaxed", "euphoric", "happy", "uplifted", "calm"],
    traits: ["frosty", "potent", "terpy"],
    potency: "strong",
    note: "Cookies' creamy-gas Gelato cross — frosty and balanced.",
  },
  {
    name: "OZ Kush",
    aliases: ["OZK"],
    type: "hybrid",
    aromas: ["sweet", "fruity", "gassy", "tropical"],
    flavors: ["sweet", "fruity", "tropical", "gassy"],
    effects: ["euphoric", "relaxed", "happy", "uplifted", "calm"],
    traits: ["frosty", "potent", "terpy", "dense-buds"],
    potency: "strong",
    note: "Zkittlez candy crossed into OG gas — parent of RS11 and Studio 54.",
  },
  {
    name: "Moonbow",
    aliases: ["Moonbow #112"],
    type: "hybrid",
    aromas: ["sweet", "fruity", "berry", "earthy"],
    flavors: ["sweet", "fruity", "berry", "grape"],
    effects: ["relaxed", "euphoric", "happy", "calm", "body-heavy"],
    traits: ["frosty", "potent", "terpy"],
    potency: "strong",
    note: "Archive's Zkittlez × Do-Si-Dos — candy berry over a relaxing body.",
  },
  {
    name: "Orange Cookies",
    type: "hybrid",
    aromas: ["citrus", "sweet", "fruity", "earthy"],
    flavors: ["citrus", "sweet", "fruity", "creamy"],
    effects: ["uplifted", "happy", "euphoric", "relaxed", "creative"],
    traits: ["terpy", "frosty", "potent"],
    potency: "strong",
    note: "Orange citrus on a GSC base — bright, sweet daytime hybrid.",
  },
  {
    name: "Chile Verde",
    type: "hybrid",
    aromas: ["gassy", "spicy", "earthy", "herbal"],
    flavors: ["gassy", "spicy", "earthy", "herbal"],
    effects: ["relaxed", "euphoric", "happy", "body-heavy", "uplifted"],
    traits: ["gassy", "potent", "frosty", "loud-smell"],
    potency: "strong",
    note: "In House OG cross — gassy and spicy, parent of Hot Sauce.",
  },
  {
    name: "Gelato 45",
    aliases: ["Gelato #45"],
    type: "hybrid",
    aromas: ["sweet", "creamy", "gassy", "berry"],
    flavors: ["sweet", "creamy", "berry", "gassy"],
    effects: ["euphoric", "relaxed", "happy", "uplifted", "calm"],
    traits: ["frosty", "potent", "terpy", "dense-buds"],
    potency: "very-strong",
    note: "A gassier Gelato pheno — sherbet cream over fuel, parent of Project 4516.",
  },
  {
    name: "Platinum Puff",
    type: "indica",
    aromas: ["gassy", "earthy", "sweet", "skunky"],
    flavors: ["gassy", "earthy", "sweet", "woody"],
    effects: ["relaxed", "body-heavy", "sleepy", "euphoric", "couch-lock"],
    traits: ["frosty", "potent", "heavy-body", "dense-buds"],
    potency: "very-strong",
    note: "Heavy Platinum OG cross — gassy, sweet and deeply sedating.",
  },
  {
    name: "Jet Fuel Gelato",
    aliases: ["Jet Fuel Gelato 41"],
    type: "hybrid",
    aromas: ["gassy", "diesel", "sweet", "earthy"],
    flavors: ["gassy", "diesel", "sweet", "creamy"],
    effects: ["energetic", "euphoric", "uplifted", "happy", "focused"],
    traits: ["gassy", "potent", "frosty", "terpy"],
    potency: "very-strong",
    note: "Compound's diesel-and-gelato — high-octane uplift, parent of Grape Gas.",
  },
  {
    name: "Pink Guava",
    type: "hybrid",
    aromas: ["sweet", "fruity", "tropical", "floral"],
    flavors: ["sweet", "fruity", "tropical", "creamy"],
    effects: ["euphoric", "happy", "relaxed", "uplifted", "calm"],
    traits: ["frosty", "potent", "terpy"],
    potency: "strong",
    note: "OZ Kushman guava selection — tropical sweetness behind RS11 and Zoap.",
  },
  {
    name: "Rainbow Sherbet",
    aliases: ["Rainbow Sherbert"],
    type: "hybrid",
    aromas: ["sweet", "fruity", "berry", "creamy"],
    flavors: ["sweet", "fruity", "berry", "creamy"],
    effects: ["happy", "euphoric", "relaxed", "uplifted", "giggly"],
    traits: ["frosty", "terpy", "potent"],
    potency: "strong",
    note: "Sherbinski fruit-sherbet — colourful, creamy-berry sweetness.",
  },
  {
    name: "Blue Zushi",
    type: "hybrid",
    aromas: ["sweet", "fruity", "berry", "gassy"],
    flavors: ["sweet", "fruity", "berry", "mint"],
    effects: ["relaxed", "euphoric", "happy", "calm", "body-heavy"],
    traits: ["frosty", "potent", "terpy", "dense-buds"],
    potency: "very-strong",
    note: "Ten Co's Zkittlez × Kush Mints — candy-mint gas, very frosty.",
  },
  {
    name: "Super Boof",
    aliases: ["Superboof", "Blockberry"],
    type: "hybrid",
    aromas: ["sweet", "fruity", "citrus", "berry"],
    flavors: ["sweet", "fruity", "citrus", "berry"],
    effects: ["euphoric", "happy", "uplifted", "relaxed", "energetic"],
    traits: ["frosty", "potent", "terpy", "dense-buds"],
    potency: "very-strong",
    note: "Leafly Strain of the Year 2024 — cherry-citrus candy, Black Cherry Punch × Tropicana Cookies.",
  },
  {
    name: "Apple Tartz",
    type: "hybrid",
    aromas: ["sweet", "fruity", "gassy", "floral"],
    flavors: ["sweet", "fruity", "gassy", "creamy"],
    effects: ["euphoric", "happy", "relaxed", "uplifted", "creative"],
    traits: ["frosty", "potent", "terpy"],
    potency: "strong",
    note: "Apple Fritter pastry over Runtz candy — sweet-apple exotic.",
  },
  {
    name: "Lemon Cherry Push Pop",
    aliases: ["Push Pop"],
    type: "hybrid",
    aromas: ["sweet", "fruity", "citrus", "floral"],
    flavors: ["sweet", "fruity", "citrus", "berry"],
    effects: ["euphoric", "happy", "relaxed", "uplifted", "calm"],
    traits: ["frosty", "potent", "terpy"],
    potency: "strong",
    note: "Lemon Cherry Gelato selection — cherry-lemon candy, heavy bag appeal.",
  },
  {
    name: "Pink Certz",
    aliases: ["Certz"],
    type: "hybrid",
    aromas: ["sweet", "gassy", "berry", "spicy"],
    flavors: ["sweet", "grape", "gassy", "mint"],
    effects: ["relaxed", "euphoric", "happy", "uplifted", "calm"],
    traits: ["frosty", "potent", "loud-smell", "terpy"],
    potency: "very-strong",
    note: "Compound's Grape Gasoline × The Menthol — grape gas with a menthol-mint snap.",
  },
  {
    name: "Guava",
    aliases: ["Guava Cake"],
    type: "hybrid",
    aromas: ["sweet", "fruity", "tropical", "earthy"],
    flavors: ["sweet", "fruity", "tropical", "creamy"],
    effects: ["euphoric", "happy", "relaxed", "uplifted", "calm"],
    traits: ["frosty", "potent", "terpy"],
    potency: "strong",
    note: "Cookies' Gelato phenotype — bright tropical guava over cream.",
  },
  {
    name: "Black Cherry Gelato",
    type: "hybrid",
    aromas: ["sweet", "fruity", "berry", "earthy"],
    flavors: ["sweet", "fruity", "berry", "creamy"],
    effects: ["relaxed", "euphoric", "happy", "body-heavy", "calm"],
    traits: ["frosty", "potent", "terpy", "dense-buds"],
    potency: "strong",
    note: "Dark cherry over a creamy Gelato base — fruity, evening-leaning hybrid.",
  },
  {
    name: "The Menthol",
    type: "hybrid",
    aromas: ["gassy", "herbal", "earthy", "spicy"],
    flavors: ["gassy", "mint", "herbal", "earthy"],
    effects: ["relaxed", "euphoric", "happy", "uplifted", "calm"],
    traits: ["frosty", "potent", "loud-smell", "terpy"],
    potency: "very-strong",
    note: "Compound Genetics — cool menthol over gas funk, parent of Pink Certz.",
  },
  {
    name: "Wedding Pie",
    type: "hybrid",
    aromas: ["sweet", "fruity", "earthy", "berry"],
    flavors: ["sweet", "grape", "vanilla", "berry"],
    effects: ["relaxed", "euphoric", "happy", "body-heavy", "calm"],
    traits: ["frosty", "potent", "terpy", "dense-buds"],
    potency: "strong",
    note: "Cannarado's Wedding Cake × Grape Pie — grape-and-vanilla cake, relaxing.",
  },
];

export function normalizeStrainName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, "");
}

const STRAIN_INDEX = new Map<string, StrainProfile>();
for (const strain of STRAINS) {
  STRAIN_INDEX.set(normalizeStrainName(strain.name), strain);
  for (const alias of strain.aliases ?? []) {
    STRAIN_INDEX.set(normalizeStrainName(alias), strain);
  }
}

export function findStrain(name: string): StrainProfile | null {
  const norm = normalizeStrainName(name);
  if (!norm) return null;
  const exact = STRAIN_INDEX.get(norm);
  if (exact) return exact;
  // Loose containment match for menu noise (e.g. "Gelato #41 3.5g").
  for (const [key, strain] of STRAIN_INDEX) {
    if (key.length >= 4 && (norm.includes(key) || key.includes(norm))) {
      return strain;
    }
  }
  return null;
}
