import type { StrainProfile } from "./types";

// Curated reference dataset. SOMA is not a strain encyclopedia — this set
// exists only to give the Taste Match Engine sensory anchors. Real batch
// quality always depends on grower, freshness and storage.
export const STRAINS: StrainProfile[] = [
  {
    name: "GG4",
    aliases: ["Gorilla Glue #4", "Gorilla Glue", "Original Glue", "Glue", "GG#4"],
    type: "hybrid",
    aromas: ["gassy", "earthy", "pine", "diesel"],
    flavors: ["earthy", "pine", "gassy"],
    effects: ["relaxed", "euphoric", "body-heavy", "happy", "calm"],
    traits: ["gassy", "earthy", "sticky", "loud-smell", "heavy-body", "frosty", "potent"],
    potency: "very-strong",
    note: "The benchmark gas-and-earth hybrid: heavy body, sticky resin, loud nose.",
  },
  {
    name: "Northern Lights",
    aliases: ["NL"],
    type: "indica",
    aromas: ["earthy", "pine", "sweet", "spicy"],
    flavors: ["sweet", "earthy", "pine"],
    effects: ["relaxed", "sleepy", "body-heavy", "happy", "calm"],
    traits: ["earthy", "dense-buds", "smooth", "heavy-body"],
    potency: "strong",
  },
  {
    name: "Super Lemon Haze",
    aliases: ["SLH"],
    type: "sativa",
    aromas: ["citrus", "sweet", "herbal"],
    flavors: ["citrus", "sweet", "herbal"],
    effects: ["uplifted", "energetic", "happy", "creative", "head-high"],
    traits: ["loud-smell", "terpy"],
    potency: "strong",
  },
  {
    name: "Blue Dream",
    type: "hybrid",
    aromas: ["berry", "sweet", "herbal", "fruity"],
    flavors: ["berry", "sweet", "fruity"],
    effects: ["happy", "uplifted", "relaxed", "creative", "calm"],
    traits: ["smooth", "terpy"],
    potency: "moderate",
  },
  {
    name: "OG Kush",
    aliases: ["OG"],
    type: "hybrid",
    aromas: ["gassy", "earthy", "pine", "woody"],
    flavors: ["earthy", "pine", "woody", "gassy"],
    effects: ["relaxed", "euphoric", "happy", "body-heavy", "calm"],
    traits: ["gassy", "earthy", "loud-smell", "dense-buds", "potent"],
    potency: "strong",
  },
  {
    name: "Sour Diesel",
    aliases: ["Sour D", "Sour Deez"],
    type: "sativa",
    aromas: ["diesel", "gassy", "citrus", "skunky"],
    flavors: ["gassy", "citrus", "herbal"],
    effects: ["energetic", "uplifted", "euphoric", "head-high", "creative"],
    traits: ["gassy", "loud-smell", "terpy", "potent"],
    potency: "strong",
  },
  {
    name: "Granddaddy Purple",
    aliases: ["GDP", "Grand Daddy Purple", "Granddaddy Purp"],
    type: "indica",
    aromas: ["berry", "sweet", "floral", "fruity"],
    flavors: ["grape", "berry", "sweet"],
    effects: ["relaxed", "sleepy", "body-heavy", "couch-lock", "happy"],
    traits: ["dense-buds", "smooth", "heavy-body", "frosty"],
    potency: "strong",
  },
  {
    name: "Wedding Cake",
    aliases: ["Pink Cookies", "Triangle Mints"],
    type: "hybrid",
    aromas: ["sweet", "earthy", "creamy", "spicy"],
    flavors: ["sweet", "vanilla", "earthy", "creamy"],
    effects: ["relaxed", "euphoric", "happy", "body-heavy", "calm"],
    traits: ["frosty", "dense-buds", "sticky", "potent", "terpy"],
    potency: "very-strong",
  },
  {
    name: "Gelato",
    aliases: ["Larry Bird"],
    type: "hybrid",
    aromas: ["sweet", "fruity", "berry", "creamy"],
    flavors: ["sweet", "berry", "creamy", "fruity"],
    effects: ["relaxed", "euphoric", "happy", "creative", "calm"],
    traits: ["frosty", "sticky", "terpy", "potent"],
    potency: "strong",
  },
  {
    name: "Girl Scout Cookies",
    aliases: ["GSC", "Cookies"],
    type: "hybrid",
    aromas: ["sweet", "earthy", "spicy", "herbal"],
    flavors: ["sweet", "earthy", "spicy"],
    effects: ["euphoric", "happy", "relaxed", "body-heavy", "head-high"],
    traits: ["frosty", "dense-buds", "potent", "terpy"],
    potency: "very-strong",
  },
  {
    name: "White Widow",
    type: "hybrid",
    aromas: ["earthy", "woody", "pine", "spicy"],
    flavors: ["earthy", "woody", "herbal"],
    effects: ["euphoric", "uplifted", "energetic", "happy", "creative"],
    traits: ["frosty", "loud-smell"],
    potency: "strong",
  },
  {
    name: "Jack Herer",
    aliases: ["JH", "The Jack"],
    type: "sativa",
    aromas: ["pine", "spicy", "earthy", "herbal", "citrus"],
    flavors: ["pine", "spicy", "citrus", "herbal"],
    effects: ["uplifted", "focused", "creative", "energetic", "happy"],
    traits: ["terpy", "loud-smell"],
    potency: "strong",
  },
  {
    name: "Pineapple Express",
    type: "hybrid",
    aromas: ["tropical", "fruity", "sweet", "citrus", "pine"],
    flavors: ["tropical", "fruity", "sweet", "citrus"],
    effects: ["uplifted", "happy", "energetic", "creative", "relaxed"],
    traits: ["smooth", "terpy"],
    potency: "moderate",
  },
  {
    name: "Green Crack",
    aliases: ["Green Cush"],
    type: "sativa",
    aromas: ["citrus", "fruity", "tropical", "earthy"],
    flavors: ["citrus", "fruity", "tropical"],
    effects: ["energetic", "focused", "uplifted", "happy", "head-high"],
    traits: ["loud-smell", "terpy"],
    potency: "strong",
  },
  {
    name: "Purple Punch",
    type: "indica",
    aromas: ["berry", "sweet", "fruity", "floral"],
    flavors: ["grape", "berry", "sweet", "vanilla"],
    effects: ["relaxed", "sleepy", "body-heavy", "happy", "hungry"],
    traits: ["dense-buds", "frosty", "smooth"],
    potency: "strong",
  },
  {
    name: "Zkittlez",
    aliases: ["Skittlez", "Skittles", "Island Zkittlez"],
    type: "indica",
    aromas: ["fruity", "sweet", "berry", "tropical"],
    flavors: ["fruity", "sweet", "berry", "tropical"],
    effects: ["relaxed", "happy", "calm", "euphoric", "uplifted"],
    traits: ["terpy", "frosty", "smooth"],
    potency: "moderate",
  },
  {
    name: "Runtz",
    aliases: ["White Runtz", "Pink Runtz"],
    type: "hybrid",
    aromas: ["sweet", "fruity", "tropical", "creamy"],
    flavors: ["sweet", "fruity", "creamy", "berry"],
    effects: ["euphoric", "happy", "relaxed", "uplifted", "calm"],
    traits: ["frosty", "sticky", "terpy", "potent"],
    potency: "very-strong",
  },
  {
    name: "Do-Si-Dos",
    aliases: ["Dosidos", "Dosi"],
    type: "indica",
    aromas: ["sweet", "earthy", "gassy", "floral"],
    flavors: ["sweet", "earthy", "gassy", "herbal"],
    effects: ["relaxed", "body-heavy", "couch-lock", "euphoric", "sleepy"],
    traits: ["frosty", "sticky", "heavy-body", "potent", "terpy"],
    potency: "very-strong",
  },
  {
    name: "Bruce Banner",
    aliases: ["Banner", "Bruce Banner #3"],
    type: "hybrid",
    aromas: ["diesel", "gassy", "sweet", "earthy"],
    flavors: ["diesel", "sweet", "earthy"],
    effects: ["euphoric", "energetic", "happy", "uplifted", "creative"],
    traits: ["gassy", "loud-smell", "potent", "frosty"],
    potency: "very-strong",
  },
  {
    name: "AK-47",
    aliases: ["AK47", "AK"],
    type: "hybrid",
    aromas: ["earthy", "floral", "woody", "spicy"],
    flavors: ["earthy", "woody", "floral", "spicy"],
    effects: ["uplifted", "happy", "relaxed", "creative", "calm"],
    traits: ["loud-smell", "terpy"],
    potency: "strong",
  },
  {
    name: "Trainwreck",
    type: "hybrid",
    aromas: ["pine", "citrus", "spicy", "earthy"],
    flavors: ["pine", "citrus", "spicy", "earthy"],
    effects: ["euphoric", "uplifted", "energetic", "happy", "creative"],
    traits: ["loud-smell", "terpy"],
    potency: "strong",
  },
  {
    name: "Chemdawg",
    aliases: ["Chemdog", "Chem Dawg", "Chem"],
    type: "hybrid",
    aromas: ["diesel", "gassy", "earthy", "pine"],
    flavors: ["diesel", "earthy", "gassy"],
    effects: ["euphoric", "relaxed", "happy", "head-high", "calm"],
    traits: ["gassy", "loud-smell", "sticky", "potent"],
    potency: "very-strong",
  },
  {
    name: "Durban Poison",
    aliases: ["Durban"],
    type: "sativa",
    aromas: ["pine", "spicy", "sweet", "earthy"],
    flavors: ["pine", "spicy", "sweet", "herbal"],
    effects: ["energetic", "focused", "uplifted", "creative", "happy"],
    traits: ["terpy", "dense-buds"],
    potency: "strong",
  },
  {
    name: "Skywalker OG",
    aliases: ["Skywalker"],
    type: "indica",
    aromas: ["gassy", "earthy", "herbal", "spicy"],
    flavors: ["gassy", "earthy", "herbal"],
    effects: ["relaxed", "sleepy", "body-heavy", "couch-lock", "calm"],
    traits: ["gassy", "dense-buds", "heavy-body", "potent"],
    potency: "very-strong",
  },
  {
    name: "Blueberry",
    aliases: ["Blueberry Kush"],
    type: "indica",
    aromas: ["berry", "sweet", "fruity", "earthy"],
    flavors: ["berry", "sweet", "fruity"],
    effects: ["relaxed", "happy", "sleepy", "body-heavy", "calm"],
    traits: ["smooth", "dense-buds", "terpy"],
    potency: "moderate",
  },
  {
    name: "Cherry Pie",
    type: "hybrid",
    aromas: ["sweet", "berry", "earthy", "fruity"],
    flavors: ["berry", "sweet", "earthy", "fruity"],
    effects: ["relaxed", "happy", "euphoric", "uplifted", "calm"],
    traits: ["smooth", "terpy"],
    potency: "moderate",
  },
  {
    name: "Tangie",
    type: "sativa",
    aromas: ["citrus", "sweet", "tropical", "herbal"],
    flavors: ["citrus", "sweet", "tropical"],
    effects: ["uplifted", "energetic", "happy", "creative", "focused"],
    traits: ["loud-smell", "terpy"],
    potency: "strong",
  },
  {
    name: "GMO Cookies",
    aliases: ["GMO", "Garlic Cookies", "Garlic Breath"],
    type: "indica",
    aromas: ["gassy", "earthy", "spicy", "herbal"],
    flavors: ["gassy", "earthy", "spicy", "herbal"],
    effects: ["relaxed", "body-heavy", "couch-lock", "euphoric", "sleepy"],
    traits: ["gassy", "loud-smell", "frosty", "heavy-body", "potent", "terpy"],
    potency: "very-strong",
  },
  {
    name: "Ice Cream Cake",
    aliases: ["ICC"],
    type: "indica",
    aromas: ["sweet", "creamy", "earthy"],
    flavors: ["sweet", "creamy", "vanilla", "nutty"],
    effects: ["relaxed", "body-heavy", "sleepy", "euphoric", "calm"],
    traits: ["frosty", "dense-buds", "sticky", "heavy-body", "potent"],
    potency: "very-strong",
  },
  {
    name: "Mimosa",
    type: "hybrid",
    aromas: ["citrus", "fruity", "sweet", "tropical"],
    flavors: ["citrus", "fruity", "sweet", "tropical"],
    effects: ["uplifted", "energetic", "happy", "focused", "euphoric"],
    traits: ["terpy", "loud-smell"],
    potency: "strong",
  },
  {
    name: "Triple Double OG",
    aliases: ["Triple OG", "TD OG"],
    type: "indica",
    aromas: ["gassy", "earthy", "pine", "diesel"],
    flavors: ["gassy", "earthy", "pine"],
    effects: ["relaxed", "body-heavy", "euphoric", "couch-lock", "calm"],
    traits: ["gassy", "earthy", "loud-smell", "heavy-body", "dense-buds", "potent"],
    potency: "very-strong",
    note: "Heavy gas-forward OG — close in spirit to a GG4 body profile.",
  },
  {
    name: "White Hot Guava",
    aliases: ["Hot Guava", "WHG"],
    type: "hybrid",
    aromas: ["tropical", "fruity", "sweet", "gassy"],
    flavors: ["tropical", "fruity", "sweet", "gassy"],
    effects: ["relaxed", "euphoric", "happy", "calm", "body-heavy"],
    traits: ["frosty", "sticky", "loud-smell", "terpy", "potent"],
    potency: "strong",
    note: "Guava-forward gas hybrid — fruity nose over a sticky, resinous body.",
  },
  {
    name: "Blueberry Cupcake",
    type: "hybrid",
    aromas: ["berry", "sweet", "creamy", "fruity"],
    flavors: ["berry", "sweet", "creamy", "vanilla"],
    effects: ["relaxed", "happy", "euphoric", "calm", "body-heavy"],
    traits: ["smooth", "frosty", "terpy"],
    potency: "moderate",
  },
  {
    name: "MAC",
    aliases: ["MAC 1", "Miracle Alien Cookies"],
    type: "hybrid",
    aromas: ["citrus", "sweet", "earthy", "floral", "gassy"],
    flavors: ["citrus", "sweet", "earthy", "creamy"],
    effects: ["euphoric", "happy", "uplifted", "relaxed", "creative"],
    traits: ["frosty", "loud-smell", "potent", "terpy"],
    potency: "very-strong",
  },
  {
    name: "Forbidden Fruit",
    type: "indica",
    aromas: ["fruity", "tropical", "berry", "citrus", "pine"],
    flavors: ["fruity", "tropical", "berry", "citrus"],
    effects: ["relaxed", "body-heavy", "happy", "sleepy", "calm"],
    traits: ["frosty", "dense-buds", "smooth", "terpy"],
    potency: "strong",
  },
  {
    name: "Lemon Cherry Gelato",
    aliases: ["LCG"],
    type: "hybrid",
    aromas: ["citrus", "berry", "sweet", "creamy", "fruity"],
    flavors: ["citrus", "berry", "sweet", "creamy"],
    effects: ["euphoric", "relaxed", "happy", "calm", "uplifted"],
    traits: ["frosty", "sticky", "loud-smell", "terpy", "potent"],
    potency: "very-strong",
  },
];

export function normalizeStrainName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]/g, "");
}

const STRAIN_INDEX = new Map<string, StrainProfile>();
for (const strain of STRAINS) {
  STRAIN_INDEX.set(normalizeStrainName(strain.name), strain);
  for (const alias of strain.aliases ?? []) {
    STRAIN_INDEX.set(normalizeStrainName(alias), strain);
  }
}

export function findStrain(name: string): StrainProfile | null {
  const norm = normalizeStrainName(name);
  if (!norm) return null;
  const exact = STRAIN_INDEX.get(norm);
  if (exact) return exact;
  // Loose containment match for menu noise (e.g. "Gelato #41 3.5g").
  for (const [key, strain] of STRAIN_INDEX) {
    if (key.length >= 4 && (norm.includes(key) || key.includes(norm))) {
      return strain;
    }
  }
  return null;
}
