// AUTO-GENERATED by scripts/sync-strain-images.mjs — do not edit by hand.
//
// Manifest of strains that have a generated atmospheric image committed to
// /public/strains. Card components look up by slug: when a path exists the
// card renders the photo over the family gradient; when it doesn't, the
// gradient stands alone (graceful fallback, no broken images).
//
// Workflow: drop <slug>.webp files into public/strains/, then run
//   npm run images:sync
// to regenerate this file. Commit both the images and this manifest.
export const STRAIN_IMAGES: Record<string, string> = {
  // populated by the sync script once images land in public/strains/
};

export function strainImageBySlug(slug: string): string | null {
  return STRAIN_IMAGES[slug] ?? null;
}
