// AUTO-GENERATED by scripts/generate-trace-overlay.ts from the
// trace-enrichment workflow (research + adversarial verify, per-token
// source-checked). Each entry lists its verifier confidence and the two
// lead sources. Validated here: real vocab only, disjoint from base
// aromas/flavors, capped at 4 per axis. Hand-curated entries in
// strain-trace-enrichment.ts take precedence over these on merge.
import type { TraceEnrichment } from "./strain-trace-enrichment";

export const TRACE_ENRICHMENT_GENERATED: Record<string, TraceEnrichment> = {
  // medium · https://www.leafly.com/strains/big-skunk-korean · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/big-skunk-korean
  "Big Skunk Korean": { traceAromas: ["citrus","pine"], traceFlavors: ["woody","pine"] },
  // medium · https://www.leafly.com/strains/gelato-41 · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/gelato-41
  "Gelato 41": { traceAromas: ["vanilla","citrus","pine","woody"], traceFlavors: ["citrus","woody","earthy"] },
  // medium · https://www.leafly.com/strains/nevils-wreck · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/nevils-wreck
  "Nevil's Wreck": { traceAromas: ["sweet","earthy","mint"], traceFlavors: ["sweet","earthy","woody"] },
  // medium · https://www.leafly.com/strains/b-52 · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/b-52
  "B-52": { traceAromas: ["herbal","spicy"] },
  // medium · https://www.leafly.com/strains/cherry-punch · https://muvfl.com/post/cherry-punch
  "Cherry Punch": { traceAromas: ["grape","earthy","spicy","woody"], traceFlavors: ["earthy","herbal","spicy","vanilla"] },
  // medium · https://strainy.ca/strain/sitka/white-hot-guava · https://www.klonetics.com/white-hot-guava
  "White Hot Guava": { traceAromas: ["pine","earthy","citrus"], traceFlavors: ["pine","earthy"] },
  // medium · https://askgrowers.com/strains/kali-mist-strain-review · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/kali-mist
  "Kali Mist": { traceAromas: ["woody","floral"], traceFlavors: ["citrus","woody"] },
  // medium · https://www.leafly.com/strains/lemon-og-haze · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/lemon-og-haze
  "Lemon OG Haze": { traceFlavors: ["spicy"] },
  // medium · https://www.allbud.com/marijuana-strains/hybrid/grape-gas · https://www.trycannavine.com/grape-gas-strain/
  "Grape Gas": { traceAromas: ["berry","earthy","spicy"], traceFlavors: ["spicy"] },
  // medium · https://hyperwolf.com/shop/strain/uk-cheese · https://www.strainpedia.com/uk-cheese/
  "UK Cheese": { traceAromas: ["sweet","floral"], traceFlavors: ["creamy","diesel"] },
  // low · https://www.leafly.com/strains/ocifer · https://goldleafmd.com/shop/products/2376873/grassroots-hybrid-ocifer-1-hickory-hash
  "Hickory Hash": { traceAromas: ["pine"], traceFlavors: ["pine"] },
  // medium · https://www.allbud.com/marijuana-strains/hybrid/cannatonic · https://seedsherenow.com/cannatonic-strain-review-and-information/
  "Cannatonic": { traceAromas: ["woody","spicy","fruity"], traceFlavors: ["woody","spicy","fruity"] },
  // medium · https://www.leafly.com/strains/orange-creamsicle · https://jollygreenlife.com/orange-creamsicle-strain-flavor-effects-genetics-growing-and-full-review/
  "Orange Creamsicle": { traceAromas: ["tropical"], traceFlavors: ["spicy","herbal"] },
  // high · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/lavender · https://dnagenetics.com/lavender-cannabis-strain/
  "Lavender": { traceAromas: ["woody","earthy"], traceFlavors: ["woody","earthy"] },
  // medium · https://www.strainpedia.com/pink-lemonade/ · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/pink-lemonade
  "Pink Lemonade": { traceAromas: ["earthy","herbal","mint"], traceFlavors: ["earthy","mint"] },
  // medium · https://www.leafly.com/strains/cheetah-piss · https://www.allbud.com/marijuana-strains/hybrid/cheetah-piss
  "Cheetah Piss": { traceAromas: ["creamy","mint"], traceFlavors: ["creamy","berry"] },
  // high · https://www.strainpedia.com/pink-certz/ · https://www.leafly.com/strains/pink-certz
  "Pink Certz": { traceAromas: ["citrus","vanilla","creamy","berry"], traceFlavors: ["citrus","vanilla","creamy","spicy"] },
  // medium · https://www.leafly.com/strains/harlequin · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/harlequin
  "Harlequin": { traceAromas: ["sweet","fruity"], traceFlavors: ["sweet","tropical","fruity"] },
  // medium · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/nevilles-haze · https://www.leafly.com/strains/nevilles-haze
  "Neville's Haze": { traceAromas: ["floral","skunky","woody"], traceFlavors: ["floral","woody","mint"] },
  // high · https://www.leafly.com/strains/jet-fuel · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/jet-fuel
  "Jet Fuel": { traceAromas: ["earthy","sweet"], traceFlavors: ["earthy","sweet","woody"] },
  // medium · https://en.wikipedia.org/wiki/Acapulco_Gold · https://www.cannagram.com/acapulco-gold-strain-guide/
  "Acapulco Gold": { traceAromas: ["citrus"], traceFlavors: ["citrus"] },
  // medium · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/animal-face · https://sativauniversity.com/strains/animal-face/
  "Animal Face": { traceAromas: ["mint","vanilla"], traceFlavors: ["mint","nutty"] },
  // medium · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/sherbet-sundae · https://www.jointcommerce.com/blog/sherbert-sundae-strain-a-comprehensive-strain-guide
  "Sundae Sherbert": { traceAromas: ["vanilla","woody"], traceFlavors: ["vanilla","woody"] },
  // medium · https://app.jointcommerce.com/blog/category/cannabis-101/charlottes-web-cbd-a-comprehensive-strain-guide/ · https://www.easttreecbd.com/hemp-review/charlottes-web-hemp-review-cbd/
  "Charlotte's Web": { traceAromas: ["floral","spicy"], traceFlavors: ["floral","spicy"] },
  // low · https://www.jointcommerce.com/blog/clockwork-orange-strain-a-comprehensive-strain-guide · https://www.strainpedia.com/clockwork-orange/
  "Clockwork Orange": { traceAromas: ["woody"] },
  // medium · https://www.leafly.com/strains/forbidden-fruit · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/forbidden-fruit
  "Forbidden Fruit": { traceAromas: ["floral","spicy"], traceFlavors: ["pine","spicy"] },
  // medium · https://highvendor.com/blog/mac-and-cheese-strain-review/ · https://thelibrarynj.com/mac-and-cheese-strain/
  "MAC and Cheese": { traceAromas: ["skunky","diesel","creamy","herbal"], traceFlavors: ["sweet","creamy","gassy"] },
  // medium · https://www.leafly.com/strains/jet-fuel-gelato · https://www.allbud.com/marijuana-strains/hybrid/jet-fuel-gelato
  "Jet Fuel Gelato": { traceAromas: ["berry","spicy","floral"], traceFlavors: ["berry","citrus","spicy","floral"] },
  // medium · https://www.allbud.com/marijuana-strains/hybrid/gary-poppins · https://www.leafly.com/strains/gary-poppins
  "Gary Poppins": { traceAromas: ["citrus","diesel","berry"], traceFlavors: ["citrus","berry","herbal"] },
  // medium · https://www.leafly.com/strains/white-runtz · https://www.allbud.com/marijuana-strains/hybrid/white-runtz
  "White Runtz": { traceAromas: ["citrus","berry","vanilla","earthy"], traceFlavors: ["citrus","earthy","spicy","pine"] },
  // medium · https://www.allbud.com/marijuana-strains/hybrid/fruity-pebbles-og · https://seedcellar.com/cannabis-seeds-101/fruity-pebbles-og-strain/
  "Fruity Pebbles OG": { traceAromas: ["citrus","creamy","earthy","spicy"], traceFlavors: ["citrus","earthy","spicy"] },
  // high · https://www.leafly.com/strains/pink-picasso · https://askgrowers.com/strains/pink-picasso-strain-review
  "Pink Picasso": { traceAromas: ["pine","floral"], traceFlavors: ["pine","floral"] },
  // medium · https://strngseeds.com/learn/g13-flavor-aroma-effects-and-growing-tips/ · https://www.strainpedia.com/g13/
  "G13": { traceAromas: ["citrus","spicy"], traceFlavors: ["citrus","herbal","spicy"] },
  // medium · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/white-gushers · https://funwithdizzies.com/review-of-white-gushers-strain-ideal-hybrid-for-relaxation/
  "White Gushers": { traceAromas: ["spicy","earthy","creamy"], traceFlavors: ["spicy","earthy","creamy","citrus"] },
  // medium · https://www.jointcommerce.com/blog/headbanger-strain-a-comprehensive-strain-guide · https://sativauniversity.com/strains/headbanger/
  "Headbanger": { traceAromas: ["pine","spicy","floral","mint"], traceFlavors: ["pine","spicy","fruity"] },
  // high · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/grease-monkey · https://www.strainpedia.com/grease-monkey/
  "Grease Monkey": { traceAromas: ["vanilla","creamy","grape"], traceFlavors: ["vanilla","nutty","spicy"] },
  // medium · https://www.leafly.com/strains/khalifa-kush · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/khalifa-kush
  "Khalifa Kush": { traceAromas: ["creamy"], traceFlavors: ["sweet","earthy"] },
  // medium · https://seedfinder.eu/en/strain-info/lebanese/the-landrace-team · https://therealseedcompany.com/product/lebanese-landrace-strain-cannabis-seeds/
  "Lebanese": { traceAromas: ["citrus","fruity"], traceFlavors: ["herbal"] },
  // low · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/strawberry-guava · https://www.leafly.com/strains/strawberry-guava
  "Strawberry Guava": { traceAromas: ["earthy"] },
  // medium · https://www.leafly.com/strains/la-confidential · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/la-confidential
  "LA Confidential": { traceAromas: ["citrus","spicy","herbal"], traceFlavors: ["sweet","spicy"] },
  // medium · https://www.leafly.com/strains/pink-panties · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/pink-panties
  "Pink Panties": { traceAromas: ["gassy","floral","woody"], traceFlavors: ["gassy"] },
  // low · https://flowerhouse2.cannaplanners.com/strain/slapaya/ · https://www.treehousecannabis.com/product/slapaya-flower-28g
  "Slapaya": { traceAromas: ["citrus","herbal"], traceFlavors: ["citrus","herbal"] },
  // medium · https://www.leafly.com/strains/mochi · https://www.allbud.com/marijuana-strains/hybrid/mochi
  "Mochi": { traceAromas: ["gassy","spicy","vanilla","berry"], traceFlavors: ["vanilla","nutty","berry"] },
  // high · https://www.leafly.com/strains/peanut-butter-breath · https://www.allbud.com/marijuana-strains/hybrid/peanut-butter-breath
  "Peanut Butter Breath": { traceFlavors: ["vanilla","spicy","citrus","creamy"] },
  // medium · https://www.leafly.com/strains/mac · https://www.allbud.com/marijuana-strains/hybrid/mac
  "MAC": { traceAromas: ["spicy","herbal","diesel"], traceFlavors: ["spicy","vanilla","floral"] },
  // medium · https://alienlabs.org/products/biskante · https://www.leafly.com/strains/biskante
  "Biskante": { traceAromas: ["vanilla","floral","pine"], traceFlavors: ["pine","spicy","herbal"] },
  // high · https://www.leafly.com/strains/sticky-buns · https://askgrowers.com/strains/sticky-buns-strain-review
  "Sticky Buns": { traceAromas: ["gassy","earthy"], traceFlavors: ["spicy","herbal"] },
  // medium · https://www.leafly.com/strains/alien-kush · https://www.allbud.com/marijuana-strains/hybrid/alien-kush
  "Alien Kush": { traceAromas: ["sweet","floral"], traceFlavors: ["berry","sweet"] },
  // medium · https://www.leafly.com/strains/khalifa-mints · https://khalifakush.com/pages/khalifa-mints
  "Khalifa Mints": { traceAromas: ["earthy"], traceFlavors: ["sweet"] },
  // medium · https://wayofleaf.com/cannabis/strains/major-league-bud-cannabis-strain · https://askgrowers.com/strains/major-league-bud-strain-review
  "Major League Bud": { traceAromas: ["floral","herbal"], traceFlavors: ["herbal","floral"] },
  // high · https://www.leafly.com/strains/chemdawg · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/chemdawg
  "Chemdawg": { traceAromas: ["citrus","spicy"], traceFlavors: ["pine","citrus"] },
  // medium · https://www.leafly.com/strains/pancakes · https://app.jointcommerce.com/blog/category/cannabis-101/pancakes-strain-a-comprehensive-strain-guide/
  "Pancakes": { traceAromas: ["berry","spicy"], traceFlavors: ["spicy","mint"] },
  // medium · https://www.leafly.com/strains/malawi · https://www.allbud.com/marijuana-strains/sativa/malawi-gold
  "Malawi": { traceAromas: ["citrus","tropical","pine","fruity"], traceFlavors: ["fruity","tropical"] },
  // medium · https://askgrowers.com/strains/alien-technology-strain-review · https://www.timelessvapes.com/alien-technology-strain-review/
  "Alien Tech": { traceAromas: ["vanilla"], traceFlavors: ["vanilla"] },
  // medium · https://www.leafly.com/strains/chemdawg-91 · https://www.allbud.com/marijuana-strains/hybrid/chem-91
  "Chem 91": { traceAromas: ["citrus"], traceFlavors: ["citrus","pine","spicy"] },
  // medium · https://www.leafly.com/strains/birthday-cake-kush · https://www.allbud.com/marijuana-strains/hybrid/birthday-cake-kush
  "Birthday Cake": { traceAromas: ["skunky","citrus"], traceFlavors: ["nutty","fruity","citrus"] },
  // medium · https://www.allbud.com/marijuana-strains/hybrid/jacks-cleaner · https://www.leafly.com/strains/jacks-cleaner
  "Jack's Cleaner": { traceAromas: ["woody"], traceFlavors: ["woody","spicy"] },
  // medium · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/acdc · https://www.leafly.com/strains/acdc
  "ACDC": { traceAromas: ["berry","sweet","woody"], traceFlavors: ["berry","sweet","fruity","spicy"] },
  // medium · https://www.leafly.com/strains/motorbreath · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/motorbreath
  "Motorbreath": { traceAromas: ["pine"], traceFlavors: ["pine","spicy","citrus"] },
  // medium · https://www.leafly.com/strains/gelato-cake · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/gelato-cake
  "Gelato Cake": { traceAromas: ["gassy","spicy","berry"], traceFlavors: ["pine","spicy"] },
  // medium · https://www.leafly.com/strains/jelly-donutz · https://www.strainpedia.com/jelly-donutz/
  "Jelly Donutz": { traceAromas: ["vanilla","earthy","citrus"], traceFlavors: ["citrus"] },
  // low · https://shop.mandalaseeds.com/products/moroccan-beldia · https://www.leafly.com/strains/moroccan-kush
  "Moroccan": { traceFlavors: ["mint"] },
  // medium · https://www.strainpedia.com/gmo/ · https://alienlabs.org/blogs/strains/gmo-cannabis-strain-flavor-potency-review
  "Golden GMO": { traceAromas: ["spicy","citrus","herbal"], traceFlavors: ["sweet","citrus","spicy"] },
  // high · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/sunset-sherbet · https://www.canapuff.com/blogs/cannabis/sunset-sherbet-strain-guide
  "Sunset Sherbet": { traceAromas: ["earthy","spicy","tropical","skunky"], traceFlavors: ["earthy","spicy","tropical","vanilla"] },
  // high · https://abstraxtech.com/blogs/learn/ice-cream-cake-get-to-know-your-favorite-strain · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/ice-cream-cake
  "Ice Cream Cake": { traceAromas: ["gassy","floral","citrus","spicy"], traceFlavors: ["citrus","cheese","earthy"] },
  // medium · https://rareharvest.net/blogs/strain-library/high-octane-og-weed-effects · https://www.ilovegrowingmarijuana.com/strains/high-octane-og-strain/
  "High Octane OG": { traceAromas: ["spicy"], traceFlavors: ["spicy"] },
  // medium · https://www.strainpedia.com/hollands-hope/ · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/hollands-hope
  "Holland's Hope": { traceAromas: ["floral","citrus","skunky"], traceFlavors: ["citrus","herbal","mint","sweet"] },
  // medium · https://app.jointcommerce.com/blog/category/cannabis-101/arjans-ultra-haze-1-a-comprehensive-strain-guide/ · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/arjans-ultra-haze-1
  "Arjan's Haze": { traceAromas: ["earthy"], traceFlavors: ["earthy"] },
  // medium · https://www.leafly.com/strains/purple-gelato · https://leafwell.com/cannabis-strains/purple-gelato
  "Purple Gelato": { traceAromas: ["mint","citrus","vanilla"], traceFlavors: ["mint","spicy"] },
  // high · https://www.leafly.com/strains/lemon-tree · https://www.allbud.com/marijuana-strains/hybrid/lemon-tree
  "Lemon Tree": { traceAromas: ["pine","skunky","herbal"], traceFlavors: ["pine"] },
  // medium · https://dnagenetics.com/chems-sister-cannabis-strain/ · https://www.leafly.com/strains/chems-sister
  "Chem's Sister": { traceAromas: ["woody","spicy","herbal","pine"], traceFlavors: ["spicy"] },
  // medium · https://www.allbud.com/marijuana-strains/hybrid/genius · https://www.jointcommerce.com/blog/genius-by-unknown-or-legendary-a-comprehensive-strain-guide
  "Genius": { traceAromas: ["woody","floral","diesel"], traceFlavors: ["sweet","earthy"] },
  // low · https://www.allbud.com/marijuana-strains/hybrid/garlic-bud · https://www.leafly.com/strains/garlic-bud
  "Garlic Bud": { traceAromas: ["herbal"] },
  // medium · https://www.leafly.com/strains/sundae-driver · https://www.allbud.com/marijuana-strains/hybrid/sundae-driver
  "Sundae Driver": { traceFlavors: ["berry"] },
  // medium · https://www.leafly.com/strains/super-lemon-haze · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/super-lemon-haze
  "Super Lemon Haze": { traceAromas: ["earthy","skunky"] },
  // medium · https://www.allbud.com/marijuana-strains/sativa/nepalese · https://www.leafly.com/strains/nepalese
  "Nepalese": { traceAromas: ["floral"], traceFlavors: ["floral"] },
  // medium · https://www.leafly.com/strains/banana-punch · https://www.allbud.com/marijuana-strains/hybrid/banana-punch
  "Banana Punch": { traceFlavors: ["pine","spicy"] },
  // medium · https://www.leafly.com/strains/tres-dawg · https://www.allbud.com/marijuana-strains/hybrid/tres-dawg
  "Tres Dawg": { traceAromas: ["spicy"], traceFlavors: ["spicy","herbal","floral","pine"] },
  // medium · https://www.leafly.com/strains/power-plant · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/power-plant
  "Power Plant": { traceAromas: ["pine","citrus"], traceFlavors: ["pine","citrus","herbal"] },
  // medium · https://www.leafly.com/strains/white-shark · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/great-white-shark
  "Great White Shark": { traceAromas: ["tropical"], traceFlavors: ["spicy","mint","fruity"] },
  // medium · https://seedsherenow.com/blueberry-cupcake-strain-blueberry-muffin-x-wedding-cake/ · https://neptuneseedbank.com/blueberry-cupcake-strain-review-grow-tips/
  "Blueberry Cupcake": { traceAromas: ["vanilla","gassy","earthy"], traceFlavors: ["earthy","spicy"] },
  // medium · https://app.jointcommerce.com/blog/category/cannabis-101/garlic-juice-strain-a-comprehensive-strain-guide/ · https://sandiegocannabistimes.com/west-coast-cure-garlic-juice/
  "Garlic Juice": { traceAromas: ["tropical"], traceFlavors: ["woody","spicy","herbal","creamy"] },
  // medium · https://www.leafly.com/strains/banana-daddy · https://www.allbud.com/marijuana-strains/hybrid/banana-daddy
  "Banana Daddy": { traceAromas: ["spicy","citrus"], traceFlavors: ["spicy"] },
  // medium · https://www.allbud.com/marijuana-strains/hybrid/lemon-thai · https://www.leafly.com/strains/lemon-thai
  "Lemon Thai": { traceAromas: ["floral","earthy"], traceFlavors: ["earthy","spicy"] },
  // medium · https://www.leafly.com/strains/death-star · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/death-star
  "Death Star": { traceAromas: ["citrus","sweet"], traceFlavors: ["citrus","sweet","spicy","herbal"] },
  // medium · https://www.leafly.com/strains/aspen-og · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/aspen-og
  "Aspen OG": { traceAromas: ["sweet","berry"], traceFlavors: ["sweet","berry","diesel","spicy"] },
  // medium · https://www.hytiva.com/strains/hybrid/citral · https://indacloud.co/blogs/citral-strain/
  "Citral": { traceFlavors: ["earthy"] },
  // medium · https://seedsherenow.com/moroccan-peaches-strain-review/ · https://www.leafly.com/strains/moroccan-peaches
  "Moroccan Peaches": { traceAromas: ["floral","spicy","woody","gassy"], traceFlavors: ["spicy","woody","floral"] },
  // high · https://www.leafly.com/strains/durban-poison · https://silverstemcannabis.com/news-articles/durban-poison-strain-review-energetic-sweet-and-classic
  "Durban Poison": { traceAromas: ["citrus"], traceFlavors: ["citrus"] },
  // medium · https://www.leafly.com/strains/georgia-pie · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/georgia-pie
  "Georgia Pie": { traceAromas: ["earthy","vanilla","gassy","berry"], traceFlavors: ["nutty","vanilla","berry","earthy"] },
  // medium · https://www.leafly.com/strains/ed-rosenthal-super-bud · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/ed-rosenthal-super-bud
  "Ed Rosenthal Super Bud": { traceAromas: ["earthy","woody","spicy"], traceFlavors: ["spicy"] },
  // medium · https://www.leafly.com/strains/mazar-i-sharif · https://www.strainpedia.com/mazar/
  "Mazar": { traceAromas: ["citrus","sweet","skunky","fruity"], traceFlavors: ["sweet","fruity"] },
  // medium · https://www.leafly.com/strains/panama-red · https://www.allbud.com/marijuana-strains/sativa/panama-red
  "Panama Red": { traceAromas: ["tropical","citrus","floral"], traceFlavors: ["tropical","herbal"] },
  // low · https://www.leafly.com/strains/og-eddy-lepp · https://www.allbud.com/marijuana-strains/hybrid/og-eddy-lepp
  "Eddy OG": { traceFlavors: ["earthy","sweet"] },
  // high · https://www.leafly.com/strains/blue-dream · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/blue-dream
  "Blue Dream": { traceAromas: ["citrus","spicy","earthy","pine"], traceFlavors: ["citrus","spicy","earthy","herbal"] },
  // medium · https://www.leafly.com/strains/chocolope · https://kurvana.com/a-look-at-the-chocolope-strain-reviews-grow-tips-and-terpenes/
  "Chocolope": { traceAromas: ["fruity","citrus"], traceFlavors: ["fruity","citrus"] },
  // medium · https://www.leafly.com/strains/jack-the-ripper · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/jack-the-ripper
  "Jack the Ripper": { traceAromas: ["tropical","sweet","earthy"], traceFlavors: ["tropical","earthy","woody"] },
  // medium · https://www.leafly.com/strains/face-mints · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/face-mints
  "Face Mints": { traceAromas: ["herbal"], traceFlavors: ["spicy","sweet"] },
  // high · https://www.leafly.com/strains/mango-kush · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/mango-kush
  "Mango Kush": { traceAromas: ["pine","citrus","spicy","skunky"], traceFlavors: ["pine","citrus","herbal"] },
  // medium · https://www.leafly.com/strains/white-widow · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/white-widow
  "White Widow": { traceAromas: ["citrus"], traceFlavors: ["citrus","sweet","fruity"] },
  // medium · https://www.leafly.com/strains/sunset-mints · https://www.allbud.com/marijuana-strains/hybrid/sunset-mints
  "Sunset Mintz": { traceAromas: ["spicy","earthy","citrus"], traceFlavors: ["spicy","earthy","citrus","tropical"] },
  // medium · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/ringos-gift · https://app.jointcommerce.com/blog/category/cannabis-101/ringos-gift-cbd-a-comprehensive-strain-guide/
  "Ringo's Gift": { traceFlavors: ["spicy","sweet","citrus"] },
  // medium · https://www.leafly.com/strains/lost-coast-og · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/lost-coast-og
  "Lost Coast OG": { traceAromas: ["woody","tropical"], traceFlavors: ["sweet","spicy"] },
  // medium · https://www.leafly.com/strains/papaya · https://abstraxtech.com/blogs/learn/get-to-know-your-favorite-strain-papaya
  "Papaya": { traceAromas: ["spicy","floral"], traceFlavors: ["spicy","creamy"] },
  // low · https://www.leafly.com/strains/orange-crush · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/orange-crush
  "Orange Crush": { traceAromas: ["earthy"], traceFlavors: ["earthy"] },
  // medium · https://www.leafly.com/strains/snow-lotus · https://app.jointcommerce.com/blog/category/cannabis-101/snow-lotus-by-bodhi-seeds-a-comprehensive-strain-guide/
  "Snow Lotus": { traceAromas: ["woody","herbal"], traceFlavors: ["fruity","creamy"] },
  // medium · https://www.leafly.com/strains/tiramisu · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/tiramisu
  "Tiramisu": { traceAromas: ["fruity","citrus","floral"], traceFlavors: ["spicy","herbal"] },
  // low · https://app.jointcommerce.com/blog/category/cannabis-101/unveiling-jungle-gemz-a-deep-dive-into-a-captivating-cannabis-experience/ · https://planetnugg.com/product/jungle-gemz-3-5g/
  "Jungle Gemz": { traceFlavors: ["earthy","herbal"] },
  // medium · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/banana-cream · https://app.jointcommerce.com/blog/category/cannabis-101/banana-cream-strain-a-comprehensive-strain-guide/
  "Banana Cream": { traceFlavors: ["spicy"] },
  // medium · https://www.allbud.com/marijuana-strains/hybrid/bog-bubble · https://app.jointcommerce.com/blog/category/cannabis-101/bog-bubble-strain-a-comprehensive-strain-guide/
  "BOG Bubble": { traceFlavors: ["grape","floral","earthy"] },
  // medium · https://www.leafly.com/strains/the-white · https://www.strainpedia.com/the-white/
  "The White": { traceAromas: ["spicy","citrus","sweet","creamy"] },
  // medium · https://www.leafly.com/strains/white-russian · https://www.strainpedia.com/white-russian/
  "White Russian": { traceAromas: ["citrus","floral","pine"], traceFlavors: ["citrus","floral"] },
  // low · https://www.leafly.com/strains/honey-bananas · https://www.allbud.com/marijuana-strains/hybrid/honey-bananas
  "Honey Banana": { traceAromas: ["mint"] },
  // medium · https://www.leafly.com/strains/secret-weapon · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/secret-weapon
  "Secret Weapon": { traceAromas: ["fruity"], traceFlavors: ["gassy","citrus","cheese"] },
  // medium · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/watermelon-zkittlez · https://www.leafly.com/strains/watermelon-zkittlez
  "Watermelon Zkittlez": { traceAromas: ["earthy","herbal","grape"], traceFlavors: ["earthy","grape"] },
  // medium · https://www.leafly.com/strains/bermuda-triangle · https://www.allbud.com/marijuana-strains/hybrid/bermuda-triangle-og
  "Bermuda Triangle": { traceAromas: ["woody"], traceFlavors: ["sweet"] },
  // medium · https://www.leafly.com/strains/blackberry · https://www.strainpedia.com/blackberry/
  "Blackberry": { traceAromas: ["earthy"], traceFlavors: ["gassy"] },
  // high · https://www.leafly.com/strains/master-kush · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/master-kush
  "Master Kush": { traceFlavors: ["sweet","citrus"] },
  // medium · https://www.leafly.com/news/strains-products/rainbow-belts-strain-strain-october-2023-highlight · https://www.leafly.com/strains/rainbow-belt
  "Rainbow Belts": { traceAromas: ["gassy","diesel","floral"], traceFlavors: ["creamy"] },
  // medium · https://askgrowers.com/strains/guava-strain-review · https://rareharvest.net/blogs/strain-library/guava-strain-info
  "Guava": { traceAromas: ["diesel","earthy","spicy"], traceFlavors: ["citrus","earthy"] },
  // medium · https://www.leafly.com/strains/hindu-kush · https://www.allbud.com/marijuana-strains/indica/hindu-kush
  "Hindu Kush": { traceAromas: ["pine","skunky","sweet"], traceFlavors: ["sweet","pine","floral","citrus"] },
  // medium · https://www.leafly.com/strains/moonbow · https://www.allbud.com/marijuana-strains/hybrid/moonbow
  "Moonbow": { traceAromas: ["diesel","creamy"], traceFlavors: ["nutty"] },
  // medium · https://www.leafly.com/strains/afghani · https://www.allbud.com/marijuana-strains/indica/afghani
  "Afghani": { traceAromas: ["floral","pine"], traceFlavors: ["pine","floral","spicy"] },
  // high · https://www.leafly.com/strains/apple-fritter · https://www.allbud.com/marijuana-strains/hybrid/apple-fritter
  "Apple Fritter": { traceAromas: ["berry","floral","herbal","spicy"], traceFlavors: ["berry","vanilla"] },
  // medium · https://www.leafly.com/strains/skunk-1 · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/skunk-1
  "Skunk #1": { traceAromas: ["citrus","cheese","herbal"], traceFlavors: ["herbal","creamy"] },
  // low · https://www.leafly.com/strains/studio-54 · https://app.jointcommerce.com/blog/category/cannabis-101/studio-54-strain-a-comprehensive-strain-guide/
  "Studio 54": { traceAromas: ["citrus","floral","woody","mint"], traceFlavors: ["citrus","woody"] },
  // medium · https://www.leafly.com/strains/apple-tartz · https://app.jointcommerce.com/blog/category/cannabis-101/apple-tartz-strain-leafly-a-comprehensive-strain-guide/
  "Apple Tartz": { traceAromas: ["vanilla","citrus","floral"], traceFlavors: ["berry","spicy","vanilla"] },
  // medium · https://www.leafly.com/strains/apple-gelato · https://www.strainpedia.com/apple-gelato/
  "Apple Gelato": { traceAromas: ["earthy","vanilla","floral"], traceFlavors: ["vanilla"] },
  // medium · https://www.leafly.com/strains/cataract-kush · https://www.strainpedia.com/cataract-kush/
  "Cataract Kush": { traceAromas: ["spicy","sweet","herbal"], traceFlavors: ["spicy","sweet","herbal"] },
  // medium · https://www.leafly.com/strains/starfighter · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/starfighter
  "Starfighter": { traceAromas: ["gassy","sweet","vanilla","berry"], traceFlavors: ["creamy","mint","gassy"] },
  // medium · https://www.strainpedia.com/stardawg/ · https://askgrowers.com/strains/stardawg-strain-review
  "Stardawg": { traceAromas: ["citrus","spicy"], traceFlavors: ["citrus","spicy"] },
  // medium · https://www.ilovegrowingmarijuana.com/strains/blockhead/ · https://www.hytiva.com/strains/hybrid/blockhead
  "Blockhead": { traceAromas: ["citrus"], traceFlavors: ["floral","berry","sweet"] },
  // medium · https://www.leafly.com/strains/haze · https://www.allbud.com/marijuana-strains/sativa/original-haze
  "Haze": { traceAromas: ["pine","woody"], traceFlavors: ["woody","sweet"] },
  // high · https://www.leafly.com/strains/banana-kush · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/banana-kush
  "Banana Kush": { traceAromas: ["earthy","spicy","skunky","creamy"], traceFlavors: ["earthy","spicy","creamy","woody"] },
  // high · https://dnagenetics.com/sour-dubb-cannabis-strain/ · https://www.leafly.com/strains/sour-dubble
  "Sour Dubb": { traceAromas: ["sweet","fruity","tropical","pine"], traceFlavors: ["sweet","fruity","spicy","citrus"] },
  // medium · https://www.leafly.com/strains/colombian-gold · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/colombian-gold
  "Colombian Gold": { traceAromas: ["herbal"], traceFlavors: ["spicy"] },
  // medium · https://www.leafly.com/strains/white-rhino · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/white-rhino
  "White Rhino": { traceAromas: ["spicy","floral","skunky","herbal"], traceFlavors: ["spicy","herbal","floral"] },
  // medium · https://www.leafly.com/strains/acai-berry-gelato · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/acai-berry-gelato
  "Acai": { traceAromas: ["earthy","citrus","floral","mint"], traceFlavors: ["citrus","vanilla","mint","spicy"] },
  // medium · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/pineapple-og · https://www.leafly.com/strains/pineapple-og
  "Pineapple": { traceAromas: ["earthy","pine","spicy","woody"], traceFlavors: ["earthy","spicy","woody"] },
  // medium · https://www.leafly.com/strains/hells-og · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/hells-og
  "Hells OG": { traceAromas: ["sweet","spicy","herbal"], traceFlavors: ["sweet","berry","herbal","spicy"] },
  // medium · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/kandahar · https://www.leafly.com/strains/kandahar
  "Kandahar": { traceAromas: ["tropical","sweet"], traceFlavors: ["fruity","pine"] },
  // medium · https://www.leafly.com/strains/jamaican · https://www.allbud.com/marijuana-strains/sativa/jamaican
  "Jamaica": { traceAromas: ["citrus","tropical","fruity"], traceFlavors: ["citrus","tropical","fruity"] },
  // medium · https://www.leafly.com/strains/cereal-milk · https://trueterpenes.com/products/terpene-strains/flavor-infused/cereal-milk/
  "Cereal Milk": { traceAromas: ["earthy","woody","spicy"], traceFlavors: ["citrus","earthy","spicy"] },
  // high · https://www.leafly.com/strains/lemon-skunk · https://dieselhemp.com/blogs/encyclopedia/lemon-skunk
  "Lemon Skunk": { traceAromas: ["pine","floral"], traceFlavors: ["pine"] },
  // medium · https://www.leafly.com/strains/gooberry · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/goo-berry
  "Gooberry": { traceAromas: ["spicy","herbal"], traceFlavors: ["spicy","floral"] },
  // low · https://app.jointcommerce.com/blog/category/cannabis-101/gas-light-strain-a-comprehensive-strain-guide/ · https://zaharacannabis.com/product/gas-lit-ih-3-5g/
  "Gas Lit": { traceAromas: ["citrus","sweet"], traceFlavors: ["citrus","sweet"] },
  // medium · https://www.leafly.com/strains/chiesel · https://www.allbud.com/marijuana-strains/hybrid/chiesel
  "Chiesel x Burnham Redeye": { traceAromas: ["spicy","herbal"], traceFlavors: ["nutty","creamy","spicy","sweet"] },
  // medium · https://www.leafly.com/strains/pink-runtz · https://www.allbud.com/marijuana-strains/hybrid/pink-runtz
  "Pink Runtz": { traceAromas: ["floral","spicy","diesel"] },
  // medium · https://www.allbud.com/marijuana-strains/hybrid/sour-glue · https://www.leafly.com/strains/sour-glue
  "Sour Glue": { traceAromas: ["herbal","spicy"], traceFlavors: ["sweet","herbal"] },
  // medium · https://www.leafly.com/strains/critical-kush · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/critical-kush
  "Critical Kush": { traceAromas: ["pine","citrus","gassy"], traceFlavors: ["pine","citrus","woody"] },
  // medium · https://www.leafly.com/strains/honey-bun · https://www.allbud.com/marijuana-strains/hybrid/honey-bun
  "Honey Bun": { traceAromas: ["spicy"], traceFlavors: ["citrus","spicy","floral"] },
  // medium · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/lemon-g · https://www.leafly.com/strains/lemon-g
  "Lemon G": { traceFlavors: ["spicy"] },
  // medium · https://app.jointcommerce.com/blog/category/cannabis-101/gelato-45-strain-a-comprehensive-strain-guide/ · https://www.leafly.com/strains/gelato-45
  "Gelato 45": { traceAromas: ["vanilla","spicy","earthy","floral"], traceFlavors: ["citrus","earthy","floral"] },
  // high · https://seedsherenow.com/chili-verde-strain-review/ · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/chili-verde
  "Chile Verde": { traceAromas: ["floral","pine","skunky"], traceFlavors: ["floral"] },
  // medium · https://app.jointcommerce.com/blog/category/cannabis-101/manipuri-by-the-real-seed-company-a-comprehensive-strain-guide/ · https://therealseedcompany.com/product/manipuri-landrace-strain-cannabis-seeds/
  "Manipuri": { traceAromas: ["mint","woody"], traceFlavors: ["mint","herbal"] },
  // medium · https://www.leafly.com/strains/ogkb · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/ogkb
  "OGKB": { traceAromas: ["citrus","berry","spicy"], traceFlavors: ["vanilla","citrus","spicy"] },
  // medium · https://www.leafly.com/strains/snowcap · https://www.allbud.com/marijuana-strains/hybrid/snowcap
  "Snowcap": { traceAromas: ["floral","herbal","fruity"], traceFlavors: ["fruity"] },
  // high · https://www.leafly.com/strains/original-glue · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/gorilla-glue-4
  "GG4": { traceAromas: ["citrus","woody"], traceFlavors: ["spicy","sweet","citrus"] },
  // low · https://www.allbud.com/marijuana-strains/sativa/guatemala · http://www.cannapedia.cz/en/variety/guatemala
  "Highland Guatemalan": { traceAromas: ["floral","woody"], traceFlavors: ["floral"] },
  // low · https://www.strainpedia.com/bubba-kush/ · https://app.jointcommerce.com/blog/category/cannabis-101/bubba-kush-strain-a-comprehensive-strain-guide/
  "Bubba Kush": { traceFlavors: ["herbal"] },
  // medium · https://www.leafly.com/strains/nyc-diesel · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/nyc-diesel
  "NYC Diesel": { traceFlavors: ["sweet","tropical","herbal"] },
  // low · https://www.leafly.com/strains/sinai · https://www.allbud.com/marijuana-strains/sativa/sinai
  "Sinai": { traceFlavors: ["sweet"] },
  // medium · https://www.leafly.com/strains/kosher-kush · https://www.allbud.com/marijuana-strains/indica/kosher-kush
  "Kosher Kush": { traceAromas: ["citrus","gassy"], traceFlavors: ["citrus","sweet","herbal","diesel"] },
  // medium · https://www.allbud.com/marijuana-strains/hybrid/hollywood-pure-kush · https://www.leafly.com/strains/hollywood-pure-kush
  "91 Hollywood Pure Kush": { traceAromas: ["sweet"], traceFlavors: ["citrus","sweet","woody"] },
};
