// AUTO-GENERATED by scripts/generate-trace-overlay.ts from the
// trace-enrichment workflow (research + adversarial verify, per-token
// source-checked). Each entry lists its verifier confidence and the two
// lead sources. Validated here: real vocab only, disjoint from base
// aromas/flavors, capped at 4 per axis. Hand-curated entries in
// strain-trace-enrichment.ts take precedence over these on merge.
import type { TraceEnrichment } from "./strain-trace-enrichment";

export const TRACE_ENRICHMENT_GENERATED2: Record<string, TraceEnrichment> = {
  // high · https://www.leafly.com/strains/og-kush · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/og-kush
  "OG Kush": { traceAromas: ["citrus","skunky","spicy"], traceFlavors: ["citrus","spicy"] },
  // high · https://www.leafly.com/strains/sour-diesel · https://www.allbud.com/marijuana-strains/sativa-dominant-hybrid/sour-diesel
  "Sour Diesel": { traceAromas: ["earthy","spicy"], traceFlavors: ["earthy","spicy"] },
  // medium · https://www.leafly.com/strains/skywalker-og · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/skywalker-og
  "Skywalker OG": { traceAromas: ["pine","woody","citrus","berry"], traceFlavors: ["woody","sweet","diesel"] },
  // medium · https://www.leafly.com/strains/gmo-cookies · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/gmo-cookies
  "GMO Cookies": { traceAromas: ["diesel"], traceFlavors: ["sweet","diesel"] },
  // high · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/tahoe-og · https://www.stiiizy.com/blogs/learn/tahoe-og-strain
  "Tahoe OG": { traceAromas: ["citrus","herbal","spicy"], traceFlavors: ["citrus","spicy","sweet"] },
  // medium · https://www.leafly.com/strains/king-louis · https://www.cannaconnection.com/strains/king-louis-xiii
  "King Louis XIII": { traceAromas: ["citrus","woody"], traceFlavors: ["citrus","woody","herbal"] },
  // medium · https://www.leafly.com/strains/platinum-og · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/platinum-og
  "Platinum OG": { traceFlavors: ["herbal","woody"] },
  // high · https://www.leafly.com/strains/fire-og · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/fire-og
  "Fire OG": { traceAromas: ["diesel","spicy"], traceFlavors: ["pine","spicy","herbal"] },
  // high · https://www.allbud.com/marijuana-strains/hybrid/face-og · https://www.strainpedia.com/face-off-og/
  "Face Off OG": { traceAromas: ["citrus","spicy"], traceFlavors: ["citrus","spicy"] },
  // high · https://www.leafly.com/strains/alien-og · https://www.allbud.com/marijuana-strains/hybrid/alien-og
  "Alien OG": { traceAromas: ["sweet","herbal"], traceFlavors: ["woody","spicy","sweet"] },
  // low · https://www.leafly.com/strains/triple-og · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/triple-og
  "Triple Double OG": { traceAromas: ["citrus","spicy"], traceFlavors: ["citrus"] },
  // medium · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/triangle-kush · https://www.leafly.com/strains/triangle-kush
  "Triangle Kush": { traceAromas: ["woody"], traceFlavors: ["woody"] },
  // high · https://www.allbud.com/marijuana-strains/indica/northern-lights · https://www.leafly.com/strains/northern-lights
  "Northern Lights": { traceAromas: ["citrus"], traceFlavors: ["citrus"] },
  // medium · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/granddaddy-purple · https://www.leafly.com/strains/granddaddy-purple
  "Granddaddy Purple": { traceAromas: ["earthy","spicy"], traceFlavors: ["earthy","woody","pine","spicy"] },
  // medium · https://www.leafly.com/strains/sfv-og · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/sfv-og
  "SFV OG": { traceFlavors: ["spicy"] },
  // medium · https://www.leafly.com/strains/headband · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/headband
  "Headband": { traceAromas: ["creamy"], traceFlavors: ["creamy","herbal","sweet"] },
  // medium · https://www.leafly.com/strains/donny-burger · https://trueterpenes.com/products/terpene-strains/cultivar-series/donny-burger/
  "Donny Burger": { traceAromas: ["pine"], traceFlavors: ["sweet"] },
  // medium · https://www.leafly.com/strains/permanent-marker · https://labeffects.com/blog/strain-report-permanent-marker-strain
  "Permanent Marker": { traceFlavors: ["citrus","floral"] },
  // high · https://www.leafly.com/strains/gas-face · https://www.allbud.com/marijuana-strains/indica-dominant-hybrid/gas-face
  "Gas Face": { traceAromas: ["mint","vanilla","creamy","sweet"], traceFlavors: ["citrus","mint","creamy","sweet"] },
};
