// Validate the workflow's trace-note proposals and emit a generated overlay.
// - keeps only real vocab tokens
// - drops any token already in the strain's base aromas/flavors
// - caps each axis so "trace" stays a faint layer, not a re-tag
// - reports everything filtered, and any name that doesn't resolve
import { readFileSync, writeFileSync } from "node:fs";
import { findStrain, normalizeStrainName } from "../src/lib/strain-data";
import { AROMAS, FLAVORS } from "../src/lib/vocab";

const OUT = process.env.WF_OUT!;
const GEN = process.env.GEN_OUT || "src/lib/strain-trace-enrichment.generated.ts";
const EXPORT = process.env.EXPORT_NAME || "TRACE_ENRICHMENT_GENERATED";
const CAP = 4;

const aromaVocab = new Set(AROMAS.map((o) => o.value));
const flavorVocab = new Set(FLAVORS.map((o) => o.value));

type Entry = {
  name: string;
  traceAromas: string[];
  traceFlavors: string[];
  sources: string[];
  confidence: string;
};

const raw = JSON.parse(readFileSync(OUT, "utf8"));
const entries: Entry[] = raw.result.entries;

const stats = { in: entries.length, kept: 0, empty: 0, unresolved: [] as string[], droppedInvalid: 0, droppedBaseDup: 0, capped: 0, tokensAdded: 0 };

const clean = (
  toks: string[],
  vocab: Set<string>,
  base: string[],
): string[] => {
  const baseSet = new Set(base);
  const seen = new Set<string>();
  const out: string[] = [];
  for (const t of toks ?? []) {
    if (!vocab.has(t)) { stats.droppedInvalid++; continue; }
    if (baseSet.has(t)) { stats.droppedBaseDup++; continue; }
    if (seen.has(t)) continue;
    seen.add(t);
    out.push(t);
  }
  if (out.length > CAP) { stats.capped++; return out.slice(0, CAP); }
  return out;
};

const lines: string[] = [];
for (const e of entries) {
  const s = findStrain(e.name);
  if (!s) { stats.unresolved.push(e.name); continue; }
  const tA = clean(e.traceAromas, aromaVocab, s.aromas ?? []);
  const tF = clean(e.traceFlavors, flavorVocab, s.flavors ?? []);
  if (tA.length === 0 && tF.length === 0) { stats.empty++; continue; }
  stats.kept++;
  stats.tokensAdded += tA.length + tF.length;
  const parts: string[] = [];
  if (tA.length) parts.push(`traceAromas: ${JSON.stringify(tA)}`);
  if (tF.length) parts.push(`traceFlavors: ${JSON.stringify(tF)}`);
  const src = (e.sources ?? []).slice(0, 2).join(" · ");
  lines.push(`  // ${e.confidence} · ${src}`);
  lines.push(`  ${JSON.stringify(s.name)}: { ${parts.join(", ")} },`);
}

const header = `// AUTO-GENERATED by scripts/generate-trace-overlay.ts from the
// trace-enrichment workflow (research + adversarial verify, per-token
// source-checked). Each entry lists its verifier confidence and the two
// lead sources. Validated here: real vocab only, disjoint from base
// aromas/flavors, capped at ${CAP} per axis. Hand-curated entries in
// strain-trace-enrichment.ts take precedence over these on merge.
import type { TraceEnrichment } from "./strain-trace-enrichment";

export const ${EXPORT}: Record<string, TraceEnrichment> = {
${lines.join("\n")}
};
`;

writeFileSync(GEN, header);
console.log("STATS", JSON.stringify(stats, null, 2));
